"use client";

import { useEffect, useState } from "react";
import { fortuneIndices } from "@/lib/fortune/daily-fortune.mjs";
import { pickUnique, randomInt } from "@/lib/random";
import { tarotDeck, type TarotCard } from "@/lib/fortune/tarot-deck";
import type { Locale } from "@/i18n/routing";

const tarotText = {
  ko:{question:"질문 (선택)",questionHint:"질문은 이 기기에서만 사용되며 저장되거나 전송되지 않습니다.",yourQuestion:"입력한 질문",spread:"카드 배열",one:"오늘의 카드 1장",three:"과거 · 현재 · 미래 3장",topic:"관심 주제",general:"종합",love:"연애",money:"금전",work:"직장 · 학업",draw:"카드 뽑기",again:"다시 뽑기",upright:"정방향",reversed:"역방향",positions:["과거","현재","미래"],privacy:"질문과 결과는 서버로 보내지 않으며 이 페이지를 벗어나면 입력 내용은 보관되지 않습니다.",note:"타로 해석은 오락과 자기성찰을 위한 참고용입니다. 미래를 확정하거나 중요한 재정·건강·법률 결정을 대신하지 않습니다."},
  en:{question:"Question (optional)",questionHint:"Your question stays on this device; it is not stored or sent.",yourQuestion:"Your question",spread:"Spread",one:"One card for today",three:"Past · Present · Future",topic:"Focus",general:"General",love:"Love",money:"Money",work:"Work · Study",draw:"Draw cards",again:"Draw again",upright:"Upright",reversed:"Reversed",positions:["Past","Present","Future"],privacy:"Your question and reading are not sent to a server. Input is not retained after you leave this page.",note:"Tarot readings are for entertainment and self-reflection. They do not predict the future or replace important financial, health, or legal judgment."},
  ja:{question:"質問（任意）",questionHint:"質問はこの端末内だけで使われ、保存・送信されません。",yourQuestion:"入力した質問",spread:"スプレッド",one:"今日のカード1枚",three:"過去・現在・未来の3枚",topic:"テーマ",general:"全体",love:"恋愛",money:"金運",work:"仕事・学業",draw:"カードを引く",again:"もう一度引く",upright:"正位置",reversed:"逆位置",positions:["過去","現在","未来"],privacy:"質問と結果はサーバーに送信されず、ページを離れると入力内容は保持されません。",note:"タロットは娯楽と自己理解のための参考です。未来を断定したり、重要な金融・健康・法律上の判断に代わるものではありません。"},
  zh:{question:"问题（可选）",questionHint:"问题仅在此设备上使用，不会保存或发送。",yourQuestion:"输入的问题",spread:"牌阵",one:"今日单张牌",three:"过去 · 现在 · 未来三张牌",topic:"主题",general:"综合",love:"感情",money:"金钱",work:"工作 · 学业",draw:"抽牌",again:"重新抽牌",upright:"正位",reversed:"逆位",positions:["过去","现在","未来"],privacy:"问题和结果不会发送到服务器，离开此页面后输入内容不会保留。",note:"塔罗解读仅供娱乐和自我反思，不代表确定的未来，也不能替代重要的财务、健康或法律判断。"},
} as const;

const dailyText = {
  ko:{birth:"생년월일",run:"오늘의 운세 보기",again:"다시 보기",date:"기준 날짜",total:"종합운",money:"금전운",love:"연애운",work:"직장 · 학업운",condition:"컨디션",number:"행운의 숫자",color:"행운의 색",line:"오늘의 한 줄",privacy:"생년월일은 오늘 날짜와 결과를 계산하는 동안 브라우저 안에서만 사용합니다. 입력값은 저장하거나 서버에 보내지 않습니다.",note:"운세는 오락과 자기성찰을 위한 참고 정보입니다. 중요한 재정·건강·법률 결정은 신뢰할 수 있는 전문 정보와 판단을 기준으로 하세요.",invalid:"생년월일을 입력해 주세요."},
  en:{birth:"Date of birth",run:"See today's fortune",again:"Refresh reading",date:"For",total:"Overall",money:"Money",love:"Relationships",work:"Work · Study",condition:"Well-being",number:"Lucky number",color:"Lucky color",line:"A note for today",privacy:"Your birth date is used only in this browser to calculate today's reading. It is not stored or sent to a server.",note:"This reading is for entertainment and reflection. Use reliable professional information for important financial, health, or legal decisions.",invalid:"Enter a valid date of birth."},
  ja:{birth:"生年月日",run:"今日の運勢を見る",again:"もう一度見る",date:"対象日",total:"総合運",money:"金運",love:"恋愛運",work:"仕事・学業運",condition:"コンディション",number:"ラッキーナンバー",color:"ラッキーカラー",line:"今日のひとこと",privacy:"生年月日は今日の結果を計算するためにブラウザー内だけで使います。保存やサーバー送信はしません。",note:"この運勢は娯楽と自己理解のための参考です。重要な金融・健康・法律上の判断には、信頼できる専門情報をご利用ください。",invalid:"有効な生年月日を入力してください。"},
  zh:{birth:"出生日期",run:"查看今日运势",again:"重新查看",date:"日期",total:"综合运势",money:"财运",love:"感情运",work:"工作 · 学业运",condition:"状态",number:"幸运数字",color:"幸运颜色",line:"今日寄语",privacy:"出生日期仅在浏览器中用于计算今日结果，不会保存或发送到服务器。",note:"本结果仅供娱乐与自我反思。重要的财务、健康或法律决定请依据可靠的专业信息。",invalid:"请输入有效的出生日期。"},
} as const;

const dailyPools: Record<Locale, {total:string[]; money:string[]; love:string[]; work:string[]; condition:string[]; line:string[]; colors:string[]}> = {
 ko:{total:["차분히 우선순위를 정하면 하루의 흐름이 한결 또렷해집니다.","작은 기회를 알아차리고 무리 없는 속도로 이어가 보세요.","주변의 의견을 듣되 마지막 기준은 자신의 상황에 두세요.","미뤄 둔 일을 한 단계만 진행해도 만족감이 커질 수 있습니다.","계획에 여유를 두면 예상 밖의 변화에도 유연하게 대응할 수 있습니다.","오늘은 완벽함보다 꾸준한 실행에 힘이 실립니다."],money:["지출 전 필요한 이유를 잠깐 확인하면 계획을 지키기 쉽습니다.","새로운 결정보다 현재 예산을 정리하는 데 집중해 보세요.","작은 절약 습관이 마음의 여유를 만드는 데 도움이 됩니다.","가격과 조건을 비교한 뒤 결정하면 불필요한 지출을 줄일 수 있습니다.","큰 결제는 서두르지 말고 정보를 충분히 확인하세요."],love:["먼저 상대의 이야기를 듣고 솔직한 마음을 부드럽게 전해 보세요.","짧은 안부나 감사 표현이 관계에 온기를 더할 수 있습니다.","상대의 반응을 단정하지 말고 대화로 확인하는 편이 좋습니다.","자신의 감정과 경계를 함께 존중하는 시간을 가져 보세요.","새로운 만남은 편안한 대화와 공통 관심사에서 시작될 수 있습니다."],work:["할 일을 작게 나누면 집중을 되찾기 쉽습니다.","중요한 내용은 한 번 더 확인하고 핵심을 간결하게 공유하세요.","혼자 해결하기보다 필요한 도움을 일찍 요청해 보세요.","급한 일과 중요한 일을 구분하면 우선순위가 선명해집니다.","새 아이디어는 메모해 두고 실행 가능한 한 단계부터 시작하세요."],condition:["잠깐 몸을 움직이거나 화면에서 눈을 떼며 쉬어 보세요.","수분과 규칙적인 식사를 챙기면 일상 리듬을 유지하기 좋습니다.","일정 사이에 짧은 휴식 시간을 미리 확보해 두세요.","오늘의 에너지에 맞춰 속도를 조절하고 무리하지 마세요.","편안한 호흡과 정돈된 주변 환경이 집중에 도움이 될 수 있습니다."],line:["한 번에 한 걸음이면 충분합니다.","비교보다 자신의 속도를 살펴보세요.","질문을 잘하는 것도 좋은 시작입니다.","잠깐 쉬는 일도 계획의 일부입니다.","작은 완료가 다음 행동을 부릅니다."],colors:["청록색","남색","연두색","주황색","보라색","회색"]},
 en:{total:["A clear priority can make the day feel more manageable.","Notice a small opening and follow it at a sustainable pace.","Listen to others while weighing advice against your own circumstances.","Moving one postponed task forward may feel rewarding.","Leave room in your plan so you can adapt to changes.","Steady progress matters more than perfection today."],money:["A quick check of why you are spending can help keep your budget on track.","Focus on reviewing your current budget before making a new commitment.","A small saving habit can create more breathing room.","Compare prices and terms before deciding.","Take time to verify details before a major purchase."],love:["Listen first, then share your thoughts with kindness.","A brief check-in or expression of thanks can warm a connection.","Ask rather than assuming how someone else feels.","Make room for both your feelings and your boundaries.","A new connection can grow from an easy conversation or shared interest."],work:["Breaking a task into smaller steps can restore focus.","Double-check key details and communicate the main point clearly.","Ask for help early when a task needs another perspective.","Separating urgent work from important work can clarify priorities.","Write down a new idea and begin with one practical step."],condition:["Take a short stretch or look away from your screen for a moment.","Water and regular meals can support a steady routine.","Schedule a brief pause between commitments.","Match your pace to your energy and avoid overloading the day.","A calm breath and tidy space may help you refocus."],line:["One step at a time is enough.","Notice your own pace instead of comparing it.","A good question can be a good beginning.","Rest can be part of the plan.","A small finish can make room for the next step."],colors:["Teal","Navy","Light green","Orange","Violet","Gray"]},
 ja:{total:["優先順位を落ち着いて決めると、一日の流れが見えやすくなります。","小さな機会に気づき、無理のないペースで進めましょう。","周りの意見を聞きつつ、自分の状況に合うか考えてみてください。","後回しにしたことを一段階進めるだけでも手応えがありそうです。","予定に余白を作ると、変化にも柔軟に対応できます。","今日は完璧さより、着実な行動が力になります。"],money:["支出の目的を少し確認すると、予算を守りやすくなります。","新しい決断より、今の予算を整理してみましょう。","小さな節約の習慣が心の余裕につながります。","価格や条件を比べてから決めると安心です。","大きな買い物は急がず、情報を確認しましょう。"],love:["相手の話を聞いてから、自分の気持ちを穏やかに伝えてみましょう。","短い連絡や感謝の言葉が関係を温めるかもしれません。","相手の反応を決めつけず、会話で確かめるのがおすすめです。","自分の気持ちと境界も大切にする時間を持ちましょう。","新しい出会いは、気軽な会話や共通の関心から始まりそうです。"],work:["作業を小さく分けると集中しやすくなります。","大切な点を再確認し、要点を簡潔に共有しましょう。","一人で抱えず、必要な助けを早めに求めてみてください。","急ぎの用事と重要な仕事を分けると優先順位が明確になります。","アイデアを書き留め、実行できる一歩から始めましょう。"],condition:["軽く体を動かすか、画面から目を離して休みましょう。","水分や規則的な食事で生活のリズムを整えましょう。","予定の合間に短い休憩を確保しておくとよさそうです。","今日の体力に合わせてペースを調整しましょう。","深呼吸や整った環境が集中を助けることがあります。"],line:["一歩ずつで大丈夫です。","比べるより、自分のペースを見つめましょう。","よい質問がよい始まりになることも。","休むことも計画の一部です。","小さな完了が次の行動につながります。"],colors:["青緑","紺","黄緑","オレンジ","紫","グレー"]},
 zh:{total:["先理清优先事项，一天的节奏会更清晰。","留意一个小机会，并以可持续的步调推进。","听取他人意见，也结合自身情况做判断。","把一件搁置的事推进一步，就可能获得成就感。","计划留有余地，面对变化会更从容。","今天稳步行动比追求完美更重要。"],money:["消费前确认用途，有助于遵守预算。","先整理现有预算，再考虑新的决定。","小小的节约习惯可以增加从容感。","比较价格与条件后再做决定。","重要支出别急于决定，先核实信息。"],love:["先倾听对方，再温和表达自己的想法。","一句问候或感谢可能让关系更温暖。","不要猜测对方的反应，通过交流确认。","也给自己的感受与界限留出空间。","新的关系可能从轻松交谈或共同兴趣开始。"],work:["把任务拆小，有助于重新集中注意力。","再次确认重点，并清楚简洁地沟通。","需要不同视角时，尽早寻求帮助。","区分紧急与重要事项，优先级会更清楚。","记下新点子，从一个可执行的小步骤开始。"],condition:["简单伸展一下，或暂时把视线从屏幕移开。","补充水分并规律进餐，有助于维持日常节奏。","在行程之间预留短暂休息。","根据精力调整速度，不要安排过满。","平稳呼吸与整洁环境可能有助于重新专注。"],line:["一步一步来就足够了。","关注自己的节奏，而非比较。","提出好问题也是好的开始。","休息也可以是计划的一部分。","完成一件小事，为下一步腾出空间。"],colors:["青绿色","藏青色","浅绿色","橙色","紫色","灰色"]},
};

export function TarotWorkspace({ locale }: { locale: Locale }) {
  const t = tarotText[locale];
  const [question, setQuestion] = useState("");
  const [spread, setSpread] = useState<"one"|"three">("one");
  const [topic, setTopic] = useState<"general"|"love"|"money"|"work">("general");
  const [draw, setDraw] = useState<{card:TarotCard; reversed:boolean}[]>([]);
  function deal() { setDraw(pickUnique(tarotDeck, spread === "one" ? 1 : 3).map((card) => ({ card, reversed: randomInt(0, 1) === 1 }))); }
  const labels = [t.general,t.love,t.money,t.work];
  const topicKeys = ["general","love","money","work"] as const;
  return <section className="rounded-3xl border border-violet-200 bg-white p-5 shadow-sm sm:p-7">
    <label htmlFor="tarot-question" className="block text-sm font-semibold">{t.question}</label><input id="tarot-question" value={question} onChange={(e)=>setQuestion(e.target.value)} maxLength={240} className="mt-2 w-full rounded-xl border border-slate-300 p-3" aria-describedby="tarot-question-hint"/><p id="tarot-question-hint" className="mt-1 text-xs text-slate-500">{t.questionHint}</p>
    <div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm">{t.spread}<select value={spread} onChange={(e)=>setSpread(e.target.value as "one"|"three")} className="mt-1 block min-h-11 w-full rounded-lg border p-2"><option value="one">{t.one}</option><option value="three">{t.three}</option></select></label><label className="text-sm">{t.topic}<select value={topic} onChange={(e)=>setTopic(e.target.value as typeof topic)} className="mt-1 block min-h-11 w-full rounded-lg border p-2">{topicKeys.map((key,i)=><option key={key} value={key}>{labels[i]}</option>)}</select></label></div>
    <button type="button" onClick={deal} className="mt-5 min-h-12 rounded-xl bg-violet-700 px-6 py-3 font-semibold text-white hover:bg-violet-800">{draw.length?t.again:t.draw}</button>
    {draw.length>0&&<div aria-live="polite" className="mt-6">{question.trim()&&<p className="mb-3 rounded-xl bg-violet-50 p-3 text-sm"><span className="font-semibold">{t.yourQuestion}: </span>{question.trim()}</p>}{spread==="three"&&<p className="mb-3 text-sm text-slate-600">{t.topic}: {t[topic]}</p>}<div className="grid gap-4 sm:grid-cols-3">{draw.map(({card,reversed},i)=><article key={card.id} className="rounded-2xl border border-violet-200 bg-gradient-to-b from-violet-50 to-white p-5"><p className="text-xs font-semibold uppercase tracking-wide text-violet-700">{spread==="one"?t[topic]:t.positions[i]}</p><h2 className="mt-3 text-xl font-bold">{card.name[locale]}</h2><p className="mt-1 text-xs font-semibold text-slate-500">{reversed?t.reversed:t.upright}</p><p className="mt-4 leading-7 text-slate-700">{card[reversed?"reversed":"upright"][locale]}</p><p className="mt-3 text-sm text-violet-800">{card.keywords[locale].join(" · ")}</p></article>)}</div></div>}
    <p className="mt-5 rounded-xl bg-emerald-50 p-4 text-sm leading-6 text-emerald-900">{t.privacy}</p><p className="mt-3 text-sm leading-6 text-slate-600">{t.note}</p>
  </section>;
}

export function DailyFortuneWorkspace({ locale }: { locale: Locale }) {
  const t = dailyText[locale]; const p = dailyPools[locale];
  const [today,setToday]=useState("");
  useEffect(()=>{const d=new Date();const value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;const id=window.setTimeout(()=>setToday(value),0);return()=>window.clearTimeout(id);},[]);
  const [birth,setBirth]=useState(""); const [result,setResult]=useState<number[]|null>(null); const [error,setError]=useState("");
  function calculate(){ if(!birth||birth>today){setError(t.invalid);setResult(null);return;} setError(""); setResult(fortuneIndices(birth,today,[p.total.length,p.money.length,p.love.length,p.work.length,p.condition.length,6,p.colors.length,p.line.length])); }
  const blocks=[{label:t.total,pool:p.total},{label:t.money,pool:p.money},{label:t.love,pool:p.love},{label:t.work,pool:p.work},{label:t.condition,pool:p.condition}];
  return <section className="rounded-3xl border border-amber-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-end"><label htmlFor="fortune-birth" className="text-sm font-semibold">{t.birth}<input id="fortune-birth" type="date" max={today} value={birth} onChange={e=>{setBirth(e.target.value);setError("");}} className="mt-1 block min-h-11 w-full rounded-lg border p-2 sm:w-64"/></label><button type="button" onClick={calculate} className="min-h-11 rounded-xl bg-amber-600 px-5 py-3 font-semibold text-white hover:bg-amber-700">{result?t.again:t.run}</button></div>
    {error&&<p role="alert" className="mt-3 text-sm text-rose-700">{error}</p>}
    {result&&<div aria-live="polite" className="mt-6"><p className="text-sm text-slate-500">{t.date}: <time dateTime={today}>{today}</time></p><div className="mt-3 grid gap-3 sm:grid-cols-2">{blocks.map((block,i)=><article key={block.label} className="rounded-2xl border border-amber-100 bg-amber-50/60 p-4"><h2 className="font-semibold">{block.label}</h2><p className="mt-2 leading-7 text-slate-700">{block.pool[result[i]]}</p></article>)}</div><div className="mt-3 grid gap-3 sm:grid-cols-3"><article className="rounded-xl bg-violet-50 p-4"><h2 className="text-sm font-semibold">{t.number}</h2><p className="mt-1 text-2xl font-bold">{result[5]+1}</p></article><article className="rounded-xl bg-violet-50 p-4"><h2 className="text-sm font-semibold">{t.color}</h2><p className="mt-1 text-lg font-bold">{p.colors[result[6]]}</p></article><article className="rounded-xl bg-violet-50 p-4 sm:col-span-1"><h2 className="text-sm font-semibold">{t.line}</h2><p className="mt-1 leading-6">{p.line[result[7]]}</p></article></div></div>}
    <p className="mt-5 rounded-xl bg-emerald-50 p-4 text-sm leading-6 text-emerald-900">{t.privacy}</p><p className="mt-3 text-sm leading-6 text-slate-600">{t.note}</p>
  </section>;
}
