"use client";

import { useState } from "react";
import type { Locale } from "@/i18n/routing";
import { randomInt } from "@/lib/random";

type Ladder={players:string[];outcomes:string[];rungs:boolean[][];ends:number[]};
const labels:Record<Locale,Record<string,string>>={ko:{players:"참가자 (2~10명)",outcomes:"결과 (참가자와 같은 수)",make:"사다리 생성",select:"경로를 확인할 참가자",result:"전체 결과",error:"참가자와 결과를 2~10개씩 같은 수로 입력하세요.",copy:"결과 복사"},en:{players:"Participants (2–10)",outcomes:"Outcomes (same number)",make:"Generate ladder",select:"Choose a path to highlight",result:"All results",error:"Enter the same number of 2–10 participants and outcomes.",copy:"Copy results"},ja:{players:"参加者 (2～10人)",outcomes:"結果 (参加者と同じ数)",make:"あみだくじを作成",select:"経路を表示する参加者",result:"全結果",error:"参加者と結果を同じ数（2～10件）入力してください。",copy:"結果をコピー"},zh:{players:"参与者（2–10人）",outcomes:"结果（数量与参与者相同）",make:"生成梯子",select:"选择要显示路径的参与者",result:"全部结果",error:"请输入数量相同的2–10名参与者和结果。",copy:"复制结果"}};

export function LadderWorkspace({locale}:{locale:Locale}){const t=labels[locale];const [playersText,setPlayersText]=useState("");const [outcomesText,setOutcomesText]=useState("");const [ladder,setLadder]=useState<Ladder|null>(null);const [selected,setSelected]=useState(0);const [error,setError]=useState("");function create(){const players=playersText.split(/\r?\n/).map(v=>v.trim()).filter(Boolean),outcomes=outcomesText.split(/\r?\n/).map(v=>v.trim()).filter(Boolean);if(players.length<2||players.length>10||players.length!==outcomes.length){setError(t.error);return}const rungs=Array.from({length:12},()=>{const row=Array(players.length-1).fill(false) as boolean[];for(let lane=0;lane<row.length;lane++){if(randomInt(0,99)<36){row[lane]=true;lane++}}return row});const ends=players.map((_,start)=>{let lane=start;for(const row of rungs){if(lane>0&&row[lane-1])lane--;else if(lane<row.length&&row[lane])lane++}return lane});setLadder({players,outcomes,rungs,ends});setSelected(0);setError("")}
  const displayLabels=(list:string[],top:boolean)=>list.map((label,i)=><div key={`${i}-${label}`} className="absolute -translate-x-1/2 truncate text-center text-xs font-medium sm:text-sm" style={{left:`${40+i*520/Math.max(1,list.length-1)}px`,top:top?"4px":"374px",width:`${Math.max(40,500/list.length)}px`}}>{label}</div>);
  function pathFor(index:number){if(!ladder)return "";const n=ladder.players.length,spacing=520/(n-1),x0=40,y0=40,dy=26;let lane=index,d=`M ${x0+lane*spacing} ${y0}`;for(let row=0;row<ladder.rungs.length;row++){const y=y0+(row+1)*dy;d+=` L ${x0+lane*spacing} ${y}`;if(lane>0&&ladder.rungs[row][lane-1]){lane--;d+=` L ${x0+lane*spacing} ${y}`}else if(lane<ladder.rungs[row].length&&ladder.rungs[row][lane]){lane++;d+=` L ${x0+lane*spacing} ${y}`}}d+=` L ${x0+lane*spacing} 365`;return d}
  const results=ladder?ladder.players.map((p,i)=>`${p} → ${ladder.outcomes[ladder.ends[i]]}`).join("\n"):"";
  return <section className="rounded-3xl border bg-white p-5 sm:p-7"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">{t.players}<textarea value={playersText} onChange={e=>setPlayersText(e.target.value)} rows={7} className="mt-1 block w-full rounded-xl border p-3"/></label><label className="text-sm font-medium">{t.outcomes}<textarea value={outcomesText} onChange={e=>setOutcomesText(e.target.value)} rows={7} className="mt-1 block w-full rounded-xl border p-3"/></label></div><button type="button" onClick={create} className="mt-4 min-h-12 rounded-xl bg-indigo-600 px-6 font-semibold text-white">{t.make}</button>{error&&<p role="alert" className="mt-3 text-sm text-rose-700">{error}</p>}{ladder&&<><label className="mt-5 block text-sm">{t.select}<select value={selected} onChange={e=>setSelected(Number(e.target.value))} className="mt-1 block w-full rounded-lg border p-3">{ladder.players.map((p,i)=><option key={`${p}-${i}`} value={i}>{p}</option>)}</select></label><div className="relative mt-6 overflow-x-auto pb-2"><div className="relative mx-auto h-[410px] w-[600px] min-w-[600px]">{displayLabels(ladder.players,true)}{displayLabels(ladder.outcomes,false)}<svg viewBox="0 0 600 390" className="absolute inset-0 h-full w-full" role="img" aria-label="Random ladder diagram"><g stroke="#94a3b8" strokeWidth="2">{ladder.players.map((_,i)=><line key={`v${i}`} x1={40+i*520/(ladder.players.length-1)} y1="40" x2={40+i*520/(ladder.players.length-1)} y2="365"/>)}{ladder.rungs.flatMap((row,r)=>row.flatMap((exists,i)=>exists?[<line key={`${r}-${i}`} x1={40+i*520/(ladder.players.length-1)} y1={66+r*26} x2={40+(i+1)*520/(ladder.players.length-1)} y2={66+r*26}/>]:[]))}</g><path d={pathFor(selected)} fill="none" stroke="#e11d48" strokeWidth="5" strokeLinecap="round"/></svg></div></div><h3 className="mt-5 font-semibold">{t.result}</h3><pre className="mt-2 whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-sm">{results}</pre><button type="button" onClick={()=>void navigator.clipboard.writeText(results)} className="mt-3 rounded-xl border px-4 py-2">{t.copy}</button></>}</section>
}
