"use client";

import { useEffect, useState } from "react";
import Image from "next/image";
import type { Locale } from "@/i18n/routing";

type Props={slug:string;locale:Locale};
type Form=Record<string,string|boolean>;
const text:Record<Locale,Record<string,string>>={
  ko:{ssid:"Wi-Fi 이름 (SSID)",password:"비밀번호",security:"보안 방식",hidden:"숨겨진 네트워크",name:"이름",phone:"전화번호",email:"이메일",company:"회사",url:"웹사이트",to:"받는 사람",subject:"제목",body:"본문",generate:"QR 코드 만들기",download:"PNG 다운로드",privacy:"입력한 정보는 이 브라우저에서 QR 코드로 변환되며 서버로 전송되지 않습니다.",required:"필수 항목을 입력해 주세요.",none:"없음",wpa:"WPA/WPA2",wep:"WEP"},
  en:{ssid:"Wi-Fi name (SSID)",password:"Password",security:"Security",hidden:"Hidden network",name:"Name",phone:"Phone",email:"Email",company:"Company",url:"Website",to:"Recipient",subject:"Subject",body:"Body",generate:"Create QR code",download:"Download PNG",privacy:"Your details are encoded in this browser and are not sent to a server.",required:"Complete the required fields.",none:"None",wpa:"WPA/WPA2",wep:"WEP"},
  ja:{ssid:"Wi-Fi名 (SSID)",password:"パスワード",security:"セキュリティ",hidden:"非公開ネットワーク",name:"名前",phone:"電話番号",email:"メールアドレス",company:"会社",url:"ウェブサイト",to:"宛先",subject:"件名",body:"本文",generate:"QRコードを作成",download:"PNGをダウンロード",privacy:"入力内容はこのブラウザー内でQRコードに変換され、サーバーには送信されません。",required:"必須項目を入力してください。",none:"なし",wpa:"WPA/WPA2",wep:"WEP"},
  zh:{ssid:"Wi-Fi名称 (SSID)",password:"密码",security:"安全类型",hidden:"隐藏网络",name:"姓名",phone:"电话号码",email:"电子邮件",company:"公司",url:"网站",to:"收件人",subject:"主题",body:"正文",generate:"生成二维码",download:"下载PNG",privacy:"输入信息仅在此浏览器中生成二维码，不会发送到服务器。",required:"请填写必填信息。",none:"无",wpa:"WPA/WPA2",wep:"WEP"}
};

export function QrWorkspace({slug,locale}:Props){
  const t=text[locale];const [form,setForm]=useState<Form>({security:"WPA",hidden:false});const [payload,setPayload]=useState("");const [error,setError]=useState("");const [downloadUrl,setDownloadUrl]=useState("");const [busy,setBusy]=useState(false);
  useEffect(()=>()=>{if(downloadUrl)URL.revokeObjectURL(downloadUrl)},[downloadUrl]);
  const field=(key:string,label:string,required=false,multiline=false)=><label key={key} className="block text-sm font-medium">{label}{required&&<span aria-hidden="true"> *</span>}{multiline?<textarea required={required} value={String(form[key]??"")} onChange={e=>setForm(v=>({...v,[key]:e.target.value}))} rows={3} className="mt-1 block w-full rounded-xl border border-slate-300 p-3"/>:<input required={required} type={key==="email"||key==="to"?"email":"text"} value={String(form[key]??"")} onChange={e=>setForm(v=>({...v,[key]:e.target.value}))} className="mt-1 block min-h-11 w-full rounded-xl border border-slate-300 p-3"/>}</label>;
  function makePayload(){const esc=(v:string)=>v.replace(/([\\;,:"])/g,"\\$1").replace(/\r?\n/g,"\\n");if(slug==="wifi-qr"){const ssid=String(form.ssid??"");if(!ssid)return "";const type=String(form.security??"WPA");return `WIFI:T:${type};S:${esc(ssid)};P:${type==="nopass"?"":esc(String(form.password??""))};H:${form.hidden?"true":"false"};;`;}if(slug==="contact-qr"){const name=String(form.name??"");if(!name)return "";return ["BEGIN:VCARD","VERSION:3.0",`FN:${esc(name)}`,form.phone?`TEL:${esc(String(form.phone))}`:"",form.email?`EMAIL:${esc(String(form.email))}`:"",form.company?`ORG:${esc(String(form.company))}`:"",form.url?`URL:${esc(String(form.url))}`:"","END:VCARD"].filter(Boolean).join("\r\n");}if(slug==="phone-qr"){const phone=String(form.phone??"").trim();return phone?`tel:${phone.replace(/[^+\d]/g,"")}`:"";}const to=String(form.to??"").trim();if(!to)return "";const query=new URLSearchParams();if(form.subject)query.set("subject",String(form.subject));if(form.body)query.set("body",String(form.body));return `mailto:${to}${query.size?`?${query}`:""}`;}
  async function generate(){setError("");const value=makePayload();if(!value){setError(t.required);return;}setBusy(true);try{const QRCode=(await import("qrcode")).default;const canvas=document.createElement("canvas");await QRCode.toCanvas(canvas,value,{width:320,margin:3,errorCorrectionLevel:"M",color:{dark:"#111827",light:"#ffffff"}});const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error("PNG encoding failed")),"image/png"));if(downloadUrl)URL.revokeObjectURL(downloadUrl);setDownloadUrl(URL.createObjectURL(blob));setPayload(value);}catch{setError("QR generation failed in this browser.")}finally{setBusy(false)}}
  return <section className="rounded-3xl border border-slate-200 bg-white p-5 sm:p-7"><p className="mb-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">🔒 {t.privacy}</p><div className="grid gap-4 sm:grid-cols-2">{slug==="wifi-qr"?<>{field("ssid",t.ssid,true)}{field("password",t.password,String(form.security)!=="nopass")}<label className="block text-sm font-medium">{t.security}<select value={String(form.security)} onChange={e=>setForm(v=>({...v,security:e.target.value}))} className="mt-1 block min-h-11 w-full rounded-xl border p-3"><option value="WPA">{t.wpa}</option><option value="WEP">{t.wep}</option><option value="nopass">{t.none}</option></select></label><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(form.hidden)} onChange={e=>setForm(v=>({...v,hidden:e.target.checked}))}/>{t.hidden}</label></>:slug==="contact-qr"?<>{field("name",t.name,true)}{field("phone",t.phone)}{field("email",t.email)}{field("company",t.company)}{field("url",t.url)}</>:slug==="phone-qr"?field("phone",t.phone,true):<>{field("to",t.to,true)}{field("subject",t.subject)}{field("body",t.body,false,true)}</>}</div><button type="button" onClick={()=>void generate()} disabled={busy} className="mt-5 min-h-12 rounded-xl bg-indigo-600 px-6 font-semibold text-white disabled:opacity-60">{busy?"…":t.generate}</button>{error&&<p role="alert" className="mt-4 text-sm text-rose-700">{error}</p>}{downloadUrl&&<div className="mt-6 flex flex-wrap items-center gap-4"><Image unoptimized src={downloadUrl} alt={`${slug} QR code`} width={240} height={240} className="h-60 w-60 rounded-xl border p-2"/><a href={downloadUrl} download={`${slug}.png`} className="rounded-xl bg-emerald-700 px-4 py-3 font-semibold text-white">{t.download}</a><details className="w-full"><summary className="cursor-pointer text-sm">{locale==="ko"?"QR 내용 확인":locale==="ja"?"QRの内容を確認":locale==="zh"?"查看二维码内容":"View encoded content"}</summary><pre className="mt-2 overflow-auto whitespace-pre-wrap break-all rounded-lg bg-slate-50 p-3 text-xs">{payload}</pre></details></div>}</section>;
}
