"use client";

import { useEffect, useMemo, useState } from "react";
import NextImage from "next/image";
import type { ToolDefinition } from "@/registry/tools";
import type { Dictionary } from "@/i18n/messages";
import type { Locale } from "@/i18n/routing";
import { processImage as processImageFile } from "@/lib/image/process-image";
import { processPdf as processPdfFile } from "@/lib/pdf/process-pdf";
import { processText as processTextTool } from "@/lib/text/process-text";
import { randomInt } from "@/lib/random";
import { QrWorkspace } from "@/components/tool/qr-workspace";

const MAX_IMAGE = 30 * 1024 * 1024;
const MAX_PDF = 50 * 1024 * 1024;

export function ToolWorkspace({ tool, locale, messages }: { tool: ToolDefinition; locale: Locale; messages: Dictionary }) {
  const isImage = tool.category === "image";
  const isPdf = tool.category === "pdf" || tool.slug === "images-to-pdf";
  const isFileTool = ["file-hash","mime-type-checker","file-extension-checker","file-size-checker","duplicate-file-checker","zip-files","bulk-file-renamer","filename-cleaner"].includes(tool.slug);
  const [files, setFiles] = useState<File[]>([]);
  const [text, setText] = useState("");
  const [secondText, setSecondText] = useState("");
  const [result, setResult] = useState("");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const [quality, setQuality] = useState(0.82);
  const [width, setWidth] = useState(800);
  const [height, setHeight] = useState(600);
  const [keepRatio, setKeepRatio] = useState(true);
  const [amount, setAmount] = useState(25);
  const [option, setOption] = useState(defaultOption(tool.slug));
  const [outputUrl, setOutputUrl] = useState("");
  const [previewUrl, setPreviewUrl] = useState("");

  useEffect(() => {
    return () => { if (outputUrl) URL.revokeObjectURL(outputUrl); };
  }, [outputUrl]);
  useEffect(() => {
    return () => { if (previewUrl) URL.revokeObjectURL(previewUrl); };
  }, [previewUrl]);
  const fileName = useMemo(() => {
    if (!files[0]) return "download";
    const stem = files[0].name.replace(/\.[^.]+$/, "").replace(/[\\/:*?"<>|]/g, "-");
    return stem || "download";
  }, [files]);
  if (["wifi-qr","contact-qr","phone-qr","email-qr"].includes(tool.slug)) return <QrWorkspace slug={tool.slug} locale={locale} />;
  if (tool.slug === "random-wheel") return <RandomWheel locale={locale} />;
  if (tool.category === "date-time") return <DateTimeTool slug={tool.slug} locale={locale} />;

  function selectFiles(list: FileList | null) {
    if (!list) return;
    const incoming = Array.from(list);
    const limit = isImage ? MAX_IMAGE : isPdf ? MAX_PDF : 100 * 1024 * 1024;
    const bad = incoming.find((file) => file.size > limit);
    if (bad) { setError(messages.errors.tooLarge.replace("{size}", String(isImage ? 30 : 50))); return; }
    if(isFileTool&&(incoming.length>100||incoming.reduce((sum,file)=>sum+file.size,0)>200*1024*1024)){setError("Select up to 100 files and 200 MB total.");return;}
    const valid = incoming.filter((file) => isImage ? (/^image\//.test(file.type) || /\.heic$/i.test(file.name)) : isPdf ? (file.type === "application/pdf" || /\.pdf$/i.test(file.name)) : true);
    if (valid.length !== incoming.length) { setError(isImage ? messages.errors.imageOnly : messages.errors.pdfOnly); return; }
    const selected = isFileTool || (isPdf && tool.slug !== "pdf-split" && tool.slug !== "pdf-delete-pages" && tool.slug !== "pdf-rotate-pages" && tool.slug !== "pdf-add-page-numbers" && tool.slug !== "pdf-watermark" && tool.slug !== "pdf-metadata-viewer" && tool.slug !== "pdf-remove-metadata") ? valid : valid.slice(0, 1);
    setFiles(selected);
    setPreviewUrl(selected[0] && isImage && !/\.heic$/i.test(selected[0].name) ? URL.createObjectURL(selected[0]) : "");
    setError(""); setResult(""); setOutputUrl("");
  }

  async function process() {
    setError(""); setResult(""); setOutputUrl(""); setBusy(true);
    try {
      if (isImage && tool.slug !== "images-to-pdf") await processImage();
      else if (isPdf) await processPdf();
      else if (isFileTool) await processFileTool();
      else await processText();
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : messages.errors.processing);
    } finally { setBusy(false); }
  }

  async function processImage() {
    const file=files[0]; if(!file) throw new Error(messages.errors.noImage);
    const processed=await processImageFile(tool.slug,file,{quality,width,height,keepRatio,amount,option,text},locale);
    if(processed.blob) setOutputUrl(URL.createObjectURL(processed.blob));
    setResult(processed.result);
  }

  async function processPdf() {
    const processed=await processPdfFile(tool.slug,files,option,text,locale);
    if(processed.blob) setOutputUrl(URL.createObjectURL(processed.blob));
    setResult(processed.result);
  }

  async function processText() {
    const processed=await processTextTool(tool.slug,text,secondText,option,amount,locale);
    if(processed.download) setOutputUrl(URL.createObjectURL(processed.download));
    setResult(processed.result);
  }
  async function processFileTool(){if(!files.length)throw new Error(messages.errors.noContent);if(tool.slug==="duplicate-file-checker"){const hashed=await Promise.all(files.map(async file=>{const digest=await crypto.subtle.digest("SHA-256",await file.arrayBuffer());return {name:file.name,hash:Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,"0")).join("")}}));const groups=new Map<string,string[]>();hashed.forEach(({name,hash})=>groups.set(hash,[...(groups.get(hash)??[]),name]));const duplicates=[...groups.values()].filter(group=>group.length>1);setResult(duplicates.length?duplicates.map((group,i)=>`Group ${i+1}:\n${group.join("\n")}`).join("\n\n"):"No identical file contents found.");return;}if(tool.slug==="zip-files"||tool.slug==="bulk-file-renamer"||tool.slug==="filename-cleaner"){const {zip}=await import("fflate");const entries:Record<string,Uint8Array>={};const report:string[]=[];for(const [index,file] of files.entries()){const original=file.name.split(/[\\/]/).pop()||`file-${index+1}`;let name=original;if(tool.slug==="bulk-file-renamer"){const [prefix="",suffix="",find="",replace=""]=text.split("\n");const dot=original.lastIndexOf(".");const stem=dot>0?original.slice(0,dot):original,ext=dot>0?original.slice(dot):"";name=`${prefix}${find?stem.replaceAll(find,replace):stem}${suffix}${ext}`;}if(tool.slug==="filename-cleaner")name=original.normalize("NFKC").replace(/[<>:"/\\|?*\u0000-\u001f]/g,"").trim().replace(/\s+/g,"_").replace(/_+/g,"_")||`file-${index+1}`;name=safeArchiveName(name);const unique=uniqueName(name,entries);entries[unique]=new Uint8Array(await file.arrayBuffer());report.push(`${original} → ${unique}`);}const data=await new Promise<Uint8Array>((resolve,reject)=>zip(entries,{level:3},(error,result)=>error?reject(error):resolve(result)));const archive=new ArrayBuffer(data.byteLength);new Uint8Array(archive).set(data);setOutputUrl(URL.createObjectURL(new Blob([archive],{type:"application/zip"})));setResult(report.join("\n"));return;}const rows=await Promise.all(files.map(async file=>{const parts=file.name.split("."),extension=parts.length>1?parts.pop()!.toLowerCase():"(none)";if(tool.slug==="file-size-checker")return `${file.name}\t${formatFileSize(file.size)}`;if(tool.slug==="file-extension-checker")return `${file.name}\t.${extension}\t${file.type||"unknown MIME"}`;if(tool.slug==="file-hash"){const digest=await crypto.subtle.digest("SHA-256",await file.arrayBuffer());return `${file.name}\tSHA-256\t${Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,"0")).join("")}`;}const bytes=new Uint8Array(await file.slice(0,16).arrayBuffer());const signature=signatureType(bytes);return `${file.name}\t${file.type||"unknown MIME"}\t${signature}`;}));setResult(rows.join("\n"));}
  const needsFiles=isImage||isPdf||isFileTool;
  const needsSecond=tool.slug==="text-compare"||tool.slug==="regex-tester"||tool.slug==="remove-characters";
  return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7" aria-label={messages.workspaceLabel.replace("{tool}", tool.title)}>
    <p className="mb-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">🔒 {messages.filePrivacy}</p>
    {needsFiles ? <div>
      <label htmlFor="tool-files" onDragOver={(e)=>e.preventDefault()} onDrop={(e)=>{e.preventDefault();selectFiles(e.dataTransfer.files);}} className="flex min-h-36 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-slate-300 bg-slate-50 p-6 text-center hover:border-indigo-400"><span className="font-semibold text-slate-800">{messages.chooseOrDrop}</span><span className="mt-2 text-sm text-slate-500">{messages.fileLimit.replace("{size}",isImage?"30":"50")}</span></label>
      <input id="tool-files" type="file" accept={isImage?"image/*,.heic,.heif":isPdf?"application/pdf,.pdf":undefined} multiple={isFileTool||tool.slug==="pdf-merge"||tool.slug==="images-to-pdf"} onChange={(e)=>selectFiles(e.target.files)} className="sr-only" />
      {files.length>0&&<div className="mt-4 rounded-xl bg-slate-50 p-4"><ul className="space-y-2">{files.map((file,i)=><li key={`${file.name}-${i}`} className="flex justify-between gap-3 text-sm"><span className="truncate">{file.name}</span><span className="shrink-0 text-slate-500">{(file.size/1024/1024).toFixed(2)} MB</span></li>)}</ul><button type="button" onClick={()=>{setFiles([]);setPreviewUrl("");setResult("");setOutputUrl("");}} className="mt-3 text-sm font-medium text-rose-700 underline">{messages.resetSelection}</button></div>}
      {previewUrl&&tool.slug!=="image-color-picker"&&<NextImage unoptimized src={previewUrl} alt={messages.selectedImageAlt} width={960} height={600} className="mt-4 max-h-72 max-w-full rounded-xl border border-slate-200 object-contain" />}
      {previewUrl&&tool.slug==="image-color-picker"&&<div className="mt-4"><p className="mb-2 text-sm">{messages.clickImageColor}</p><ColorPicker src={previewUrl} label={messages.colorPickerLabel} onPick={setResult}/></div>}
    </div> : <div className="grid gap-4 sm:grid-cols-2">
      <div><label htmlFor="input-text" className="mb-2 block text-sm font-medium">{needsSecond?messages.firstText:messages.input}</label><textarea id="input-text" value={text} onChange={(e)=>setText(e.target.value)} rows={9} placeholder={tool.slug==="timestamp-converter"?messages.timestampPlaceholder:tool.slug==="random-number"?(locale==="ko"?"최소값, 최대값 예: 1, 45":locale==="ja"?"最小値, 最大値 例: 1, 45":locale==="zh"?"最小值, 最大值 例如：1, 45":"Minimum, maximum e.g. 1, 45"):tool.slug==="color-converter"?"#3366FF":messages.textPlaceholder} className="w-full rounded-xl border border-slate-300 p-3 font-mono text-sm outline-none focus:border-indigo-400 focus:ring-4 focus:ring-indigo-100" />{tool.slug==="timestamp-converter"&&<p className="mt-2 text-xs text-slate-500">{messages.timestampHint}</p>}</div>
      {needsSecond&&<div><label htmlFor="second-text" className="mb-2 block text-sm font-medium">{messages.secondText}</label><textarea id="second-text" value={secondText} onChange={(e)=>setSecondText(e.target.value)} rows={9} className="w-full rounded-xl border border-slate-300 p-3 font-mono text-sm outline-none focus:border-indigo-400 focus:ring-4 focus:ring-indigo-100" /></div>}
    </div>}
    <ToolOptions tool={tool} locale={locale} messages={messages} {...{quality,setQuality,width,setWidth,height,setHeight,keepRatio,setKeepRatio,amount,setAmount,option,setOption,text,setText}} />
    <div className="mt-5 flex flex-wrap gap-3"><button type="button" onClick={process} disabled={busy} className="min-h-12 rounded-xl bg-indigo-600 px-6 font-semibold text-white hover:bg-indigo-700 disabled:cursor-wait disabled:opacity-60">{busy?messages.processing:tool.category==="image"||tool.category==="pdf"?messages.process:messages.run}</button><button type="button" onClick={()=>{setText("");setSecondText("");setResult("");setOutputUrl("");setError("");}} className="min-h-12 rounded-xl border border-slate-300 px-5 font-medium hover:bg-slate-50">{messages.reset}</button></div>
    <p role="status" aria-live="polite" className="sr-only">{busy?messages.processingStatus:result?messages.completedStatus:""}</p>
    {error&&<p role="alert" className="mt-4 rounded-xl bg-rose-50 p-4 text-sm text-rose-800">{error}</p>}
    {result&&<div className="mt-5"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">{messages.result}</h3>{outputUrl&&<a href={outputUrl} download={downloadName(tool.slug,fileName)} className="rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-emerald-800">{messages.download}</a>}{!needsFiles&&<button type="button" onClick={()=>void navigator.clipboard.writeText(result).catch(()=>setError(messages.errors.copy))} className="rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-medium hover:bg-slate-50">{messages.copy}</button>}</div><pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap break-words rounded-xl bg-slate-950 p-4 text-sm leading-6 text-slate-100">{result}</pre></div>}
  </section>;
}

function ToolOptions({tool,locale,messages,quality,setQuality,width,setWidth,height,setHeight,keepRatio,setKeepRatio,amount,setAmount,option,setOption,text,setText}:{tool:ToolDefinition;locale:Locale;messages:Dictionary;quality:number;setQuality:(v:number)=>void;width:number;setWidth:(v:number)=>void;height:number;setHeight:(v:number)=>void;keepRatio:boolean;setKeepRatio:(v:boolean)=>void;amount:number;setAmount:(v:number)=>void;option:string;setOption:(v:string)=>void;text:string;setText:(v:string)=>void}) {
  const slug=tool.slug;
  if (slug==="bulk-file-renamer") return <label className="mt-4 block text-sm">{localeLabel(locale,"renameRules")}<textarea value={text} onChange={e=>setText(e.target.value)} rows={4} placeholder="prefix&#10;suffix&#10;find&#10;replace" className="mt-1 block w-full rounded-lg border p-3 font-mono"/><span className="mt-1 block text-xs text-slate-500">{localeLabel(locale,"renameHint")}</span></label>;
  if (slug==="social-image-resize") return <SelectOption label={messages.option} value={option||"square"} onChange={setOption} options={[["square",localeLabel(locale,"square")],["portrait",localeLabel(locale,"portraitPreset")],["story",localeLabel(locale,"story")],["youtube",localeLabel(locale,"youtube")],["x",localeLabel(locale,"xpost")],["facebook",localeLabel(locale,"facebook")]]} />;
  if (slug==="add-text-to-image") return <label className="mt-4 block text-sm">{messages.input}<input value={text} onChange={e=>setText(e.target.value)} maxLength={160} className="mt-1 block w-full rounded-lg border p-3"/></label>;
  if (["random-number","random-name-picker","random-wheel","draw-lots","random-team-maker","random-order","dice-roller","coin-flip","password-generator","random-string-generator","uuid-generator","text-repeater","lorem-ipsum"].includes(slug)) return <div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm">{messages.generateCount}<input type="number" min="1" max={slug==="coin-flip"?1000:100} value={amount} onChange={(e)=>setAmount(Number(e.target.value))} className="mt-1 block w-full rounded-lg border p-2" /></label>{["random-number","random-name-picker","random-wheel","draw-lots"].includes(slug)&&<SelectOption label={messages.option} value={option} onChange={setOption} options={[["unique",localeLabel(locale,"noRepeat")],["repeat",localeLabel(locale,"repeat")]]} />}{slug==="dice-roller"&&<SelectOption label={messages.option} value={option||"6"} onChange={setOption} options={[["4","D4"],["6","D6"],["8","D8"],["10","D10"],["12","D12"],["20","D20"]]} />}{slug==="text-repeater"&&<label className="text-sm">{messages.option}<input value={option} onChange={(e)=>setOption(e.target.value)} placeholder=", " className="mt-1 block w-full rounded-lg border p-2" /></label>}</div>;
  if (slug==="remove-characters") return <SelectOption label={messages.option} value={option||"digits"} onChange={setOption} options={[["digits",localeLabel(locale,"digits")],["latin",localeLabel(locale,"latin")],["hangul",localeLabel(locale,"hangul")],["special",localeLabel(locale,"special")],["custom",localeLabel(locale,"custom")]]} />;
  if (["image-compress","jpg-to-webp","png-to-webp","png-to-jpg","webp-to-jpg","heic-to-jpg"].includes(slug)) return <label className="mt-5 block text-sm">{messages.quality}: {Math.round(quality*100)}% <input type="range" min="0.2" max="1" step="0.01" value={quality} onChange={(e)=>setQuality(Number(e.target.value))} className="mt-2 block w-full accent-indigo-600" /></label>;
  if (slug==="image-resize") return <div className="mt-5 flex flex-wrap items-end gap-4"><label className="text-sm">{messages.width}<input type="number" min="1" max="12000" value={width} onChange={(e)=>setWidth(Number(e.target.value))} className="mt-1 block w-28 rounded-lg border p-2" /></label><label className="text-sm">{messages.height}<input type="number" min="1" max="12000" value={height} onChange={(e)=>setHeight(Number(e.target.value))} disabled={keepRatio} className="mt-1 block w-28 rounded-lg border p-2 disabled:bg-slate-100" /></label><label className="flex min-h-10 items-center gap-2 text-sm"><input type="checkbox" checked={keepRatio} onChange={(e)=>setKeepRatio(e.target.checked)} />{messages.keepRatio}</label></div>;
  if (slug==="image-rotate") return <SelectOption label={messages.rotation} value={option} onChange={setOption} options={[["90","90°"],["180","180°"],["270","270°"]]} />;
  if (slug==="image-flip") return <SelectOption label={messages.flipDirection} value={option} onChange={setOption} options={[["horizontal",messages.horizontal],["vertical",messages.vertical]]} />;
  if (slug==="image-crop") return <SelectOption label={messages.cropAspect} value={option} onChange={setOption} options={[["1",messages.square],["1.7778",messages.landscape],["0.75",messages.portrait]]} />;
  if (["image-brightness","image-contrast","image-blur","image-pixelate"].includes(slug)) return <label className="mt-5 block text-sm">{slug==="image-brightness"?messages.brightness:slug==="image-contrast"?messages.contrast:slug==="image-blur"?messages.blur: messages.mosaic}: {amount}<input type="range" min={slug==="image-blur"?0:slug==="image-pixelate"?4:0} max={slug==="image-blur"?100:slug==="image-pixelate"?80:200} value={amount} onChange={(e)=>setAmount(Number(e.target.value))} className="mt-2 block w-full accent-indigo-600" /></label>;
  if (["remove-spaces","sort-lines","text-case-converter","json-formatter","base64","url-encode-decode","timestamp-converter"].includes(slug)) {
    const opts=slug==="remove-spaces"?[["all",messages.removeAllSpaces],["collapse",messages.collapseSpaces]]:slug==="sort-lines"?[["asc",messages.ascending],["desc",messages.descending]]:slug==="text-case-converter"?[["lower",messages.lowercase],["upper",messages.uppercase],["title",messages.titleCase]]:slug==="json-formatter"?[["format",messages.prettyPrint],["minify",messages.minify]]:slug==="base64"?[["encode",messages.encode],["decode",messages.decode]]:slug==="url-encode-decode"?[["encode",messages.encode],["decode",messages.decode]]:[["seconds",messages.unixSeconds],["milliseconds",messages.unixMilliseconds],["date",messages.enterDate]];
    return <SelectOption label={messages.option} value={option} onChange={setOption} options={opts as [string,string][]} />;
  }
  if (slug==="uuid-generator") return <label className="mt-4 block text-sm">{messages.generateCount}<input type="number" min="1" max="100" value={amount} onChange={(e)=>setAmount(Number(e.target.value))} className="ml-3 w-24 rounded-lg border p-2" /></label>;
  if (["pdf-split","pdf-delete-pages"].includes(slug)) return <label className="mt-4 block text-sm">{messages.pageRange}<input value={option} onChange={(e)=>setOption(e.target.value)} placeholder="1, 3-5" className="mt-1 block w-full rounded-lg border p-3" /></label>;
  if (slug==="pdf-reorder-pages") return <label className="mt-4 block text-sm">{messages.pageOrder}<input value={option} onChange={(e)=>setOption(e.target.value)} placeholder="3,1,2" className="mt-1 block w-full rounded-lg border p-3" /></label>;
  if (slug==="pdf-rotate-pages") return <SelectOption label={messages.rotation} value={option} onChange={setOption} options={[["90","90°"],["180","180°"],["270","270°"]]} />;
  if (slug==="pdf-watermark") return <label className="mt-4 block text-sm">{messages.watermark}<input value={text} onChange={(e)=>setText(e.target.value)} placeholder="Woori Tools" className="mt-1 block w-full rounded-lg border p-3" /></label>;
  if (slug==="uuid-generator") return null;
  return null;
}
function SelectOption({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:[string,string][]}){return <label className="mt-4 block text-sm">{label}<select value={value} onChange={(e)=>onChange(e.target.value)} className="mt-1 block w-full rounded-lg border border-slate-300 bg-white p-3">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>;}
function defaultOption(slug:string){return slug==="image-rotate"||slug==="pdf-rotate-pages"?"90":slug==="image-flip"?"horizontal":slug==="image-crop"?"1":slug==="sort-lines"?"asc":slug==="text-case-converter"?"lower":slug==="json-formatter"?"format":slug==="base64"||slug==="url-encode-decode"?"encode":slug==="timestamp-converter"?"seconds":slug==="remove-spaces"?"all":["random-number","random-name-picker","random-wheel","draw-lots"].includes(slug)?"unique":"";}
function localeLabel(locale:Locale,key:string){const labels:Record<Locale,Record<string,string>>={ko:{noRepeat:"중복 없이",repeat:"중복 허용",digits:"숫자",latin:"영문",hangul:"한글",special:"특수문자",custom:"사용자 지정",square:"Instagram 정사각형",portraitPreset:"Instagram 세로",story:"Instagram 스토리",youtube:"YouTube 썸네일",xpost:"X 게시물",facebook:"Facebook 게시물",renameRules:"줄마다 접두사, 접미사, 찾을 글자, 바꿀 글자를 입력",renameHint:"생략한 줄은 무시합니다. 변경본은 ZIP으로 받습니다."},en:{noRepeat:"Without repeats",repeat:"Allow repeats",digits:"Digits",latin:"Latin letters",hangul:"Korean characters",special:"Special characters",custom:"Custom string",square:"Instagram square",portraitPreset:"Instagram portrait",story:"Instagram story",youtube:"YouTube thumbnail",xpost:"X post",facebook:"Facebook post",renameRules:"Enter prefix, suffix, find, and replace on separate lines",renameHint:"Leave a line empty to skip that rule. Renamed copies are downloaded as a ZIP."},ja:{noRepeat:"重複なし",repeat:"重複あり",digits:"数字",latin:"英字",hangul:"ハングル",special:"記号",custom:"指定文字列",square:"Instagram正方形",portraitPreset:"Instagram縦長",story:"Instagramストーリー",youtube:"YouTubeサムネイル",xpost:"X投稿",facebook:"Facebook投稿",renameRules:"接頭辞、接尾辞、検索文字、置換文字を各行に入力",renameHint:"空欄の規則は無視します。変更後のファイルはZIPで保存します。"},zh:{noRepeat:"不重复",repeat:"允许重复",digits:"数字",latin:"英文字母",hangul:"韩文",special:"特殊字符",custom:"自定义字符",square:"Instagram方形",portraitPreset:"Instagram竖版",story:"Instagram限时动态",youtube:"YouTube缩略图",xpost:"X帖子",facebook:"Facebook帖子",renameRules:"每行输入前缀、后缀、查找内容和替换内容",renameHint:"留空的规则将跳过。重命名后的副本将打包为ZIP下载。"}};return labels[locale][key]??key;}
function downloadName(slug:string,stem:string){if(slug==="images-to-pdf"||slug.startsWith("pdf-"))return`${stem}-${slug==="pdf-merge"?"merged":"processed"}.pdf`;if(slug==="text-to-file")return `${stem}.txt`;if(["zip-files","bulk-file-renamer","filename-cleaner"].includes(slug))return `${slug}.zip`;const extension=slug.includes("png")||slug==="favicon-generator"?"png":slug.includes("webp")?"webp":"jpg";return`${stem}-${slug}.${extension}`;}
function safeArchiveName(value:string){return value.replace(/^[. ]+|[. ]+$/g,"").replace(/[<>:"/\\|?*\u0000-\u001f]/g,"_")||"file";}
function uniqueName(name:string,entries:Record<string,Uint8Array>){if(!entries[name])return name;const dot=name.lastIndexOf("."),stem=dot>0?name.slice(0,dot):name,ext=dot>0?name.slice(dot):"";let n=2;while(entries[`${stem} (${n})${ext}`])n++;return `${stem} (${n})${ext}`;}
function formatFileSize(size:number){if(size<1024)return `${size} B`;if(size<1024*1024)return `${(size/1024).toFixed(1)} KB`;return `${(size/1024/1024).toFixed(2)} MB`;}
function signatureType(bytes:Uint8Array){if(bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47)return "PNG signature";if(bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff)return "JPEG signature";if(String.fromCharCode(...bytes.slice(0,4))==="%PDF")return "PDF signature";if(String.fromCharCode(...bytes.slice(0,3))==="GIF")return "GIF signature";if(String.fromCharCode(...bytes.slice(0,2))==="PK")return "ZIP signature";return "Unknown signature";}
function ColorPicker({src,label,onPick}:{src:string;label:string;onPick:(v:string)=>void}){return <canvas aria-label={label} ref={(canvas)=>{if(!canvas)return;const img=new Image();img.onload=()=>{const scale=Math.min(1,800/img.width);canvas.width=img.width*scale;canvas.height=img.height*scale;canvas.getContext("2d")?.drawImage(img,0,0,canvas.width,canvas.height);};img.src=src;}} onClick={(e)=>{const canvas=e.currentTarget,rect=canvas.getBoundingClientRect(),x=Math.floor((e.clientX-rect.left)*canvas.width/rect.width),y=Math.floor((e.clientY-rect.top)*canvas.height/rect.height),data=canvas.getContext("2d")?.getImageData(x,y,1,1).data;if(data){const hex=`#${[data[0],data[1],data[2]].map((n)=>n.toString(16).padStart(2,"0")).join("").toUpperCase()}`;onPick(`${hex} · RGB(${data[0]}, ${data[1]}, ${data[2]})`);}}} className="max-h-96 max-w-full cursor-crosshair rounded-lg" />;}

function DateTimeTool({slug,locale}:{slug:string;locale:Locale}) {
  const labels:Record<Locale,Record<string,string>>={ko:{start:"시작",pause:"일시정지",resume:"계속",reset:"초기화",lap:"랩 기록",laps:"랩",hours:"시",minutes:"분",seconds:"초",remaining:"남은 시간",done:"시간 종료",cities:"세계 주요 도시",focus:"집중",break:"휴식",session:"세션"},en:{start:"Start",pause:"Pause",resume:"Resume",reset:"Reset",lap:"Lap",laps:"Laps",hours:"Hours",minutes:"Minutes",seconds:"Seconds",remaining:"Remaining",done:"Time is up",cities:"World cities",focus:"Focus",break:"Break",session:"Session"},ja:{start:"開始",pause:"一時停止",resume:"再開",reset:"リセット",lap:"ラップ",laps:"ラップ記録",hours:"時",minutes:"分",seconds:"秒",remaining:"残り時間",done:"時間終了",cities:"世界の都市",focus:"集中",break:"休憩",session:"セッション"},zh:{start:"开始",pause:"暂停",resume:"继续",reset:"重置",lap:"计圈",laps:"计圈记录",hours:"时",minutes:"分",seconds:"秒",remaining:"剩余时间",done:"时间到",cities:"世界城市",focus:"专注",break:"休息",session:"阶段"}};
  const t=labels[locale]; const [elapsed,setElapsed]=useState(0); const [running,setRunning]=useState(false); const [laps,setLaps]=useState<number[]>([]); const [hours,setHours]=useState(0); const [minutes,setMinutes]=useState(slug==="pomodoro-timer"?25:0); const [seconds,setSeconds]=useState(0); const [remaining,setRemaining]=useState(0); const [clock,setClock]=useState(0); const [mode,setMode]=useState(false); const [hasStarted,setHasStarted]=useState(false);
  useEffect(()=>{let previous=Date.now(),timerElapsed=0;const id=window.setInterval(()=>{const now=Date.now(),delta=now-previous;setClock(now);if(running){if(slug==="stopwatch")setElapsed(v=>v+delta);else{timerElapsed+=delta;if(timerElapsed>=1000){const secondsPassed=Math.floor(timerElapsed/1000);timerElapsed%=1000;if(remaining<=secondsPassed)setRunning(false);setRemaining(v=>Math.max(0,v-secondsPassed));}}}previous=now;},250);return()=>window.clearInterval(id);},[running,slug,remaining]);
  const format=(n:number)=>{const total=Math.floor(n/1000);return `${String(Math.floor(total/3600)).padStart(2,"0")}:${String(Math.floor(total/60)%60).padStart(2,"0")}:${String(total%60).padStart(2,"0")}.${String(n%1000).padStart(3,"0")}`;};
  if(slug==="world-clock") { const cities=[["Seoul","Asia/Seoul"],["Tokyo","Asia/Tokyo"],["New York","America/New_York"],["Los Angeles","America/Los_Angeles"],["London","Europe/London"],["Paris","Europe/Paris"],["Singapore","Asia/Singapore"],["Sydney","Australia/Sydney"]] as const; return <section className="rounded-3xl border bg-white p-6"><h2 className="text-xl font-semibold">{t.cities}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{cities.map(([city,zone])=><article key={zone} className="rounded-xl bg-slate-50 p-4"><h3 className="font-medium">{city}</h3><p className="mt-1 font-mono text-2xl">{new Intl.DateTimeFormat(locale,{timeZone:zone,hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(clock)}</p><p className="text-sm text-slate-500">{new Intl.DateTimeFormat(locale,{timeZone:zone,dateStyle:"medium"}).format(clock)}</p></article>)}</div></section>; }
  if(slug==="stopwatch")return <section className="rounded-3xl border bg-white p-6 text-center"><p className="font-mono text-4xl tabular-nums sm:text-6xl">{format(elapsed)}</p><div className="mt-6 flex flex-wrap justify-center gap-3"><button className="rounded-xl bg-indigo-600 px-5 py-3 text-white" onClick={()=>setRunning(!running)}>{running?t.pause:elapsed?t.resume:t.start}</button><button className="rounded-xl border px-5 py-3" onClick={()=>{setElapsed(0);setLaps([]);setRunning(false)}}>{t.reset}</button><button disabled={!running} className="rounded-xl border px-5 py-3 disabled:opacity-50" onClick={()=>setLaps(v=>[elapsed,...v])}>{t.lap}</button></div><ol className="mt-5 space-y-2 text-left">{laps.map((lap,i)=><li key={`${lap}-${i}`} className="flex justify-between border-b py-2"><span>{t.laps} {laps.length-i}</span><span className="font-mono">{format(lap)}</span></li>)}</ol></section>;
  const begin=(next:number)=>{setRemaining(next);setRunning(true);setHasStarted(true)}; const timerMode=slug==="timer"; const total=timerMode?(hours*3600+minutes*60+seconds):mode?5*60:25*60;
  return <section className="rounded-3xl border bg-white p-6 text-center"><p className="text-sm font-medium text-slate-500">{slug==="pomodoro-timer"?`${mode?t.break:t.focus} · ${t.session}`:t.remaining}</p><p className="mt-2 font-mono text-5xl tabular-nums sm:text-6xl">{format(remaining*1000).slice(0,8)}</p>{!running&&<div className="mx-auto mt-5 grid max-w-md grid-cols-3 gap-3">{[[t.hours,hours,setHours],[t.minutes,minutes,setMinutes],[t.seconds,seconds,setSeconds]].map(([label,value,setter])=><label key={String(label)} className="text-sm">{String(label)}<input type="number" min="0" max="999" value={Number(value)} onChange={e=>(setter as (n:number)=>void)(Math.max(0,Number(e.target.value)||0))} className="mt-1 w-full rounded-lg border p-2 text-center" /></label>)}</div>}<div className="mt-5 flex flex-wrap justify-center gap-3"><button className="rounded-xl bg-indigo-600 px-5 py-3 text-white" onClick={()=>running?setRunning(false):begin(remaining||total)}>{running?t.pause:t.start}</button><button className="rounded-xl border px-5 py-3" onClick={()=>{setRunning(false);setRemaining(0);setHasStarted(false)}}>{t.reset}</button>{slug==="pomodoro-timer"&&<button className="rounded-xl border px-5 py-3" onClick={()=>{setMode(!mode);setRunning(false);setRemaining((mode?25:5)*60)}}>{mode?t.focus:t.break}</button>}</div>{hasStarted&&remaining===0&&!running&&<p aria-live="polite" className="mt-4 text-amber-700">{t.done}</p>}</section>;
}

function RandomWheel({locale}:{locale:Locale}) {
  const copy:Record<Locale,{label:string;spin:string;spinning:string;winner:string;remove:string;reset:string;placeholder:string}>={ko:{label:"항목을 줄마다 입력",spin:"룰렛 돌리기",spinning:"돌리는 중…",winner:"선택 결과",remove:"선택 항목 제거 후 다시 돌리기",reset:"초기화",placeholder:"예: 점심 메뉴\n피자\n국수"},en:{label:"Enter one choice per line",spin:"Spin the wheel",spinning:"Spinning…",winner:"Selected choice",remove:"Remove winner before next spin",reset:"Reset",placeholder:"Lunch\nPizza\nNoodles"},ja:{label:"選択肢を1行ずつ入力",spin:"ルーレットを回す",spinning:"回転中…",winner:"選ばれた項目",remove:"次の抽選前に当選項目を削除",reset:"リセット",placeholder:"ランチ\nピザ\n麺類"},zh:{label:"每行输入一个选项",spin:"旋转转盘",spinning:"旋转中…",winner:"抽中结果",remove:"下次抽选前移除该选项",reset:"重置",placeholder:"午餐\n披萨\n面食"}};
  const t=copy[locale];const [items,setItems]=useState<string[]>(()=>locale==="ko"?["항목 1","항목 2","항목 3","항목 4"]:locale==="ja"?["項目1","項目2","項目3","項目4"]:locale==="zh"?["选项1","选项2","选项3","选项4"]:["Option 1","Option 2","Option 3","Option 4"]);const [turn,setTurn]=useState(0);const [winner,setWinner]=useState("");const [spinning,setSpinning]=useState(false);const values=items.map(s=>s.trim()).filter(Boolean);const segment=values.length?360/values.length:360;const colors=["#6366f1","#0ea5e9","#10b981","#f59e0b","#ec4899","#8b5cf6"];
  function spin(){if(spinning||!values.length)return;const index=randomInt(0,values.length-1);const target=turn+1800+(360-index*segment-segment/2);setTurn(target);setWinner(values[index]);setSpinning(true);window.setTimeout(()=>setSpinning(false),4200);}
  return <section className="rounded-3xl border bg-white p-5 sm:p-7"><label htmlFor="wheel-options" className="block text-sm font-medium">{t.label}</label><textarea id="wheel-options" rows={5} value={items.join("\n")} onChange={e=>{setItems(e.target.value.split(/\r?\n/));setWinner("")}} placeholder={t.placeholder} className="mt-2 w-full rounded-xl border p-3"/><div className="mx-auto mt-6 flex max-w-md flex-col items-center"><div className="relative aspect-square w-full max-w-80"><div aria-hidden="true" className="absolute left-1/2 top-0 z-10 -translate-x-1/2 border-x-[14px] border-t-[28px] border-x-transparent border-t-rose-600"/><div aria-label={values.join(", ")} role="img" className="h-full w-full rounded-full border-4 border-white shadow-xl transition-transform duration-[4000ms] ease-out" style={{background:values.length?`conic-gradient(${values.map((_,i)=>`${colors[i%colors.length]} ${i*segment}deg ${(i+1)*segment}deg`).join(",")})`:"#cbd5e1",transform:`rotate(${turn}deg)`}}/><div className="absolute inset-0 flex items-center justify-center"><span className="rounded-full bg-white px-3 py-1 text-sm font-bold shadow">{values.length}</span></div></div><button type="button" disabled={spinning||!values.length} onClick={spin} className="mt-5 min-h-12 rounded-xl bg-indigo-600 px-6 font-semibold text-white disabled:opacity-50">{spinning?t.spinning:t.spin}</button></div>{winner&&<div className="mt-5 rounded-xl bg-emerald-50 p-4 text-center"><h3 className="font-semibold">{t.winner}</h3><p className="mt-1 text-xl">{winner}</p><label className="mt-3 inline-flex items-center gap-2 text-sm"><input type="checkbox" onChange={e=>{if(e.target.checked)setItems(old=>old.filter(item=>item.trim()!==winner))}}/>{t.remove}</label></div>}<button type="button" onClick={()=>{setItems([]);setWinner("");setTurn(0)}} className="mt-4 rounded-lg border px-4 py-2">{t.reset}</button></section>;
}
