import type { Locale } from "@/i18n/routing";

export type TarotCard = { id: string; name: Record<Locale, string>; upright: Record<Locale, string>; reversed: Record<Locale, string>; keywords: Record<Locale, string[]> };

// Original text-only Major Arcana deck. No Rider–Waite artwork or copied card descriptions.
export const tarotDeck: TarotCard[] = [
  { id:"fool",name:{ko:"바보",en:"The Fool",ja:"愚者",zh:"愚者"},upright:{ko:"새로운 출발을 앞두고 가벼운 호기심으로 가능성을 살펴보세요.",en:"A fresh start invites curiosity. Explore possibilities while staying aware of your next step.",ja:"新しい始まりの気配。好奇心を大切にしながら、次の一歩も意識しましょう。",zh:"新的开始带来好奇心。探索可能性时，也留意下一步。"},reversed:{ko:"서두르기보다 준비가 되었는지 확인하고 작은 계획부터 세워 보세요.",en:"Pause before rushing ahead. Check your preparation and begin with a small plan.",ja:"急ぐ前に準備を確認し、小さな計画から始めてみましょう。",zh:"先别急着行动，确认准备情况并从小计划开始。"},keywords:{ko:["시작","가능성"],en:["beginnings","possibility"],ja:["始まり","可能性"],zh:["开始","可能性"]}},
  { id:"magician",name:{ko:"마법사",en:"The Magician",ja:"魔術師",zh:"魔术师"},upright:{ko:"이미 가진 도구와 능력을 연결하면 생각을 실행으로 옮기기 좋습니다.",en:"Your available skills and tools can turn an idea into a practical first step.",ja:"手元にある力や道具を組み合わせると、考えを行動に移しやすいでしょう。",zh:"整合已有能力与资源，有助于把想法变成行动。"},reversed:{ko:"목표와 수단이 맞는지 점검하고 한 번에 한 가지에 집중해 보세요.",en:"Review whether your methods fit the goal, and focus on one clear action.",ja:"目的と方法が合っているか見直し、一つの行動に集中しましょう。",zh:"检查方法是否适合目标，并先专注于一件事。"},keywords:{ko:["집중","실행"],en:["focus","action"],ja:["集中","実行"],zh:["专注","行动"]}},
  { id:"priestess",name:{ko:"여사제",en:"The High Priestess",ja:"女教皇",zh:"女祭司"},upright:{ko:"바로 결론을 내리기보다 정보를 모으고 자신의 직감을 차분히 살펴보세요.",en:"Gather information before deciding, and make room to listen to your own perspective.",ja:"すぐに結論を出さず、情報を集めながら自分の感覚を見つめましょう。",zh:"先收集信息，再静下心来倾听自己的判断。"},reversed:{ko:"추측이 사실을 대신하지 않도록 확인할 수 있는 정보부터 살펴보세요.",en:"Separate assumptions from facts and look for information you can verify.",ja:"思い込みと事実を分け、確かめられる情報から見ていきましょう。",zh:"区分猜测与事实，先查找可核实的信息。"},keywords:{ko:["성찰","관찰"],en:["reflection","observation"],ja:["内省","観察"],zh:["反思","观察"]}},
  { id:"empress",name:{ko:"여황제",en:"The Empress",ja:"女帝",zh:"皇后"},upright:{ko:"돌봄과 창의성을 키울 때입니다. 꾸준히 가꾼 일이 결실을 맺도록 여유를 주세요.",en:"Nurture creativity and relationships. Give ongoing work the space it needs to grow.",ja:"創造性や人とのつながりを育てるとき。続けてきたことに成長の余地を与えましょう。",zh:"适合培育创造力与关系，给持续投入的事情留出成长空间。"},reversed:{ko:"주변을 돌보느라 자신의 필요를 미루고 있지 않은지 살펴보세요.",en:"Notice whether caring for others has pushed your own needs aside.",ja:"周りを優先するあまり、自分の必要を後回しにしていないか確認しましょう。",zh:"留意照顾他人时是否忽略了自己的需要。"},keywords:{ko:["돌봄","창의성"],en:["nurture","creativity"],ja:["育む","創造性"],zh:["培育","创造力"]}},
  { id:"emperor",name:{ko:"황제",en:"The Emperor",ja:"皇帝",zh:"皇帝"},upright:{ko:"명확한 기준과 순서를 세우면 복잡한 일을 안정적으로 다룰 수 있습니다.",en:"Clear boundaries and structure can help you handle a complex task steadily.",ja:"基準と順序を明確にすると、複雑なことにも落ち着いて取り組めます。",zh:"明确规则与步骤，有助于稳妥处理复杂事务。"},reversed:{ko:"계획이 지나치게 경직되지는 않았는지 살피고 조정 여지를 남겨 두세요.",en:"Check whether your plan has become too rigid and leave room to adjust.",ja:"計画が硬直していないか見直し、調整できる余地を残しましょう。",zh:"检查计划是否过于僵化，并留出调整空间。"},keywords:{ko:["구조","기준"],en:["structure","boundaries"],ja:["秩序","基準"],zh:["结构","规则"]}},
  { id:"hierophant",name:{ko:"교황",en:"The Hierophant",ja:"法王",zh:"教皇"},upright:{ko:"검증된 방법이나 경험자의 조언에서 배울 점을 찾아보세요.",en:"Established methods or a trusted mentor may offer a useful perspective.",ja:"実績ある方法や経験者の助言から、役立つ視点を探してみましょう。",zh:"从成熟的方法或有经验者的建议中寻找参考。"},reversed:{ko:"관습을 따르기 전에 지금의 상황과 자신의 기준에 맞는지 확인하세요.",en:"Before following convention, check whether it fits your situation and values.",ja:"慣例に従う前に、今の状況や自分の基準に合うか確かめましょう。",zh:"遵循惯例前，先确认它是否适合当前情况与自身标准。"},keywords:{ko:["배움","전통"],en:["learning","tradition"],ja:["学び","伝統"],zh:["学习","传统"]}},
  { id:"lovers",name:{ko:"연인",en:"The Lovers",ja:"恋人",zh:"恋人"},upright:{ko:"관계나 선택에서 중요한 것은 서로의 가치와 마음을 솔직히 확인하는 일입니다.",en:"In a relationship or choice, honest alignment with shared values matters.",ja:"関係や選択では、お互いの価値観や気持ちを率直に確かめることが大切です。",zh:"在关系或选择中，坦诚确认彼此的价值观与想法很重要。"},reversed:{ko:"상대의 기대만 따르지 말고 자신이 원하는 바도 분명히 표현해 보세요.",en:"Do not rely only on someone else's expectations; name what you want too.",ja:"相手の期待だけでなく、自分の希望も言葉にしてみましょう。",zh:"不要只迎合他人的期待，也清楚表达自己的想法。"},keywords:{ko:["관계","선택"],en:["connection","choice"],ja:["関係","選択"],zh:["关系","选择"]}},
  { id:"chariot",name:{ko:"전차",en:"The Chariot",ja:"戦車",zh:"战车"},upright:{ko:"방향을 정하고 집중하면 여러 요구 사이에서도 앞으로 나아갈 수 있습니다.",en:"Choose a direction and focus to move forward amid competing demands.",ja:"進む方向を決めて集中すれば、複数の課題の中でも前進できます。",zh:"确定方向并保持专注，便能在多种要求中继续前进。"},reversed:{ko:"속도를 높이기 전에 우선순위와 에너지를 다시 조정해 보세요.",en:"Revisit your priorities and pace before trying to push harder.",ja:"さらに急ぐ前に、優先順位とペースを整え直しましょう。",zh:"在加速之前，重新调整优先事项与节奏。"},keywords:{ko:["방향","의지"],en:["direction","will"],ja:["方向","意志"],zh:["方向","意志"]}},
  { id:"strength",name:{ko:"힘",en:"Strength",ja:"力",zh:"力量"},upright:{ko:"차분함과 꾸준함이 문제를 다루는 힘이 됩니다. 자신에게도 너그러워지세요.",en:"Patience and steady effort can be more effective than force. Treat yourself kindly.",ja:"力で押すより、落ち着きと粘り強さが助けになります。自分にも寛容に。",zh:"耐心与稳定行动比强硬更有效，也请善待自己。"},reversed:{ko:"기운이 소진되었다면 잠시 쉬고 부담을 나눌 방법을 찾아보세요.",en:"If you feel depleted, pause and consider how to share the load.",ja:"疲れを感じるなら少し休み、負担を分ける方法を考えましょう。",zh:"如果感到疲惫，先休息并考虑如何分担压力。"},keywords:{ko:["인내","회복"],en:["patience","resilience"],ja:["忍耐","回復"],zh:["耐心","韧性"]}},
  { id:"hermit",name:{ko:"은둔자",en:"The Hermit",ja:"隠者",zh:"隐者"},upright:{ko:"잠시 속도를 늦추고 혼자 생각할 시간을 가지면 중요한 기준이 보일 수 있습니다.",en:"A little quiet time may help you find the principle that matters most.",ja:"少し立ち止まって考える時間を持つと、大切な基準が見えてくるかもしれません。",zh:"放慢脚步独自思考，或许能看清真正重要的标准。"},reversed:{ko:"혼자 고민을 오래 끌기보다 믿을 만한 사람과 생각을 나눠 보세요.",en:"Rather than staying isolated with a concern, talk it through with someone you trust.",ja:"一人で抱え続けず、信頼できる人に考えを話してみましょう。",zh:"与其独自反复纠结，不如和信任的人聊一聊。"},keywords:{ko:["성찰","방향"],en:["reflection","guidance"],ja:["内省","道しるべ"],zh:["反思","指引"]}},
  { id:"wheel",name:{ko:"운명의 수레바퀴",en:"Wheel of Fortune",ja:"運命の輪",zh:"命运之轮"},upright:{ko:"상황의 흐름이 바뀔 수 있습니다. 변화에 대응할 준비와 유연성을 살펴보세요.",en:"Circumstances can shift. Consider how to stay prepared and adaptable.",ja:"状況が動く気配があります。変化に備え、柔軟さを保てるか考えましょう。",zh:"局势可能发生变化，想想如何做好准备并保持灵活。"},reversed:{ko:"통제하기 어려운 일에 매달리기보다 지금 선택할 수 있는 행동에 집중하세요.",en:"Focus on the actions available to you instead of what you cannot control.",ja:"変えにくいことより、今選べる行動に目を向けましょう。",zh:"把注意力放在当下可选择的行动，而非无法控制的部分。"},keywords:{ko:["변화","흐름"],en:["change","cycles"],ja:["変化","流れ"],zh:["变化","周期"]}},
  { id:"justice",name:{ko:"정의",en:"Justice",ja:"正義",zh:"正义"},upright:{ko:"사실과 기준을 차분히 비교하고 선택의 결과를 균형 있게 살펴보세요.",en:"Compare the facts and standards calmly, and consider the effects of each choice.",ja:"事実と基準を落ち着いて比べ、選択の結果を公平に考えましょう。",zh:"冷静比较事实与标准，并平衡考虑不同选择的影响。"},reversed:{ko:"한쪽에 치우친 정보가 없는지 확인하고 불확실한 부분을 분리해 보세요.",en:"Check for one-sided information and separate what remains uncertain.",ja:"偏った情報がないか確かめ、不確かな点を分けて考えましょう。",zh:"检查信息是否片面，并把不确定之处分开看待。"},keywords:{ko:["균형","판단"],en:["balance","clarity"],ja:["均衡","判断"],zh:["平衡","判断"]}},
  { id:"hanged-man",name:{ko:"매달린 사람",en:"The Hanged Man",ja:"吊るされた男",zh:"倒吊人"},upright:{ko:"잠시 멈추면 익숙한 문제를 다른 관점에서 볼 기회가 생깁니다.",en:"A pause can reveal a different way to view a familiar problem.",ja:"いったん止まることで、慣れた問題を別の角度から見られるでしょう。",zh:"暂时停下，或许能从不同角度看待熟悉的问题。"},reversed:{ko:"기다림이 도움이 되는지, 결정을 미루는 습관인지 구분해 보세요.",en:"Consider whether waiting is useful or simply postponing a decision.",ja:"待つことが有効なのか、決断を先延ばしにしているのか見極めましょう。",zh:"判断等待是否有帮助，还是只是在拖延决定。"},keywords:{ko:["관점","멈춤"],en:["perspective","pause"],ja:["視点","停止"],zh:["视角","暂停"]}},
  { id:"death",name:{ko:"죽음",en:"Death",ja:"死神",zh:"死神"},upright:{ko:"끝맺음은 새로운 공간을 만들 수 있습니다. 계속할 것과 내려놓을 것을 정리해 보세요.",en:"An ending can make room for something new. Decide what to carry forward and what to release.",ja:"終わりが新しい余地を生むこともあります。続けることと手放すことを整理しましょう。",zh:"结束也能腾出新的空间，整理哪些要继续、哪些可以放下。"},reversed:{ko:"변화를 피하고 있다면 부담이 적은 작은 전환부터 시도해 보세요.",en:"If change feels difficult, try one small transition that feels manageable.",ja:"変化を避けているなら、無理のない小さな切り替えから試しましょう。",zh:"如果难以面对变化，可以先尝试一个负担较小的调整。"},keywords:{ko:["전환","정리"],en:["transition","release"],ja:["転換","整理"],zh:["转变","整理"]}},
  { id:"temperance",name:{ko:"절제",en:"Temperance",ja:"節制",zh:"节制"},upright:{ko:"서로 다른 일정과 필요를 조율하면 무리 없이 이어갈 방법을 찾을 수 있습니다.",en:"Blending different needs and timelines can help you find a sustainable approach.",ja:"異なる予定や希望を調整すると、無理なく続ける方法が見つかりそうです。",zh:"协调不同需求与安排，有助于找到可持续的做法。"},reversed:{ko:"한쪽으로 치우친 일정이나 습관이 없는지 점검해 균형을 되찾아 보세요.",en:"Look for an imbalanced routine or commitment and make a small adjustment.",ja:"偏った予定や習慣がないか確認し、小さく整えてみましょう。",zh:"检查是否有失衡的安排或习惯，并做一点调整。"},keywords:{ko:["조율","균형"],en:["moderation","balance"],ja:["調整","均衡"],zh:["协调","平衡"]}},
  { id:"devil",name:{ko:"악마",en:"The Devil",ja:"悪魔",zh:"恶魔"},upright:{ko:"습관이나 약속이 선택을 좁히고 있지 않은지 살펴보고 가능한 대안을 찾아보세요.",en:"Notice whether a habit or obligation is narrowing your choices, then look for alternatives.",ja:"習慣や義務が選択肢を狭めていないか見直し、代案を探しましょう。",zh:"留意习惯或义务是否限制了选择，并寻找可行替代方案。"},reversed:{ko:"불편한 패턴을 알아차렸다면 도움을 구하거나 작은 경계를 세울 수 있습니다.",en:"Recognizing an unhelpful pattern is a start; support or a small boundary may help.",ja:"望ましくないパターンに気づいたら、助けを求めたり小さな境界を設けたりできます。",zh:"发现不理想的模式后，可以寻求支持或设定小小的界限。"},keywords:{ko:["습관","선택"],en:["patterns","choice"],ja:["習慣","選択"],zh:["习惯","选择"]}},
  { id:"tower",name:{ko:"탑",en:"The Tower",ja:"塔",zh:"高塔"},upright:{ko:"기존 방식이 흔들리는 상황이라면 우선 안전과 사실 확인부터 챙기세요.",en:"If familiar structures are shifting, start with safety and a clear view of the facts.",ja:"これまでの形が揺らぐときは、まず安全と事実の確認を優先しましょう。",zh:"当熟悉的结构出现变化时，先确保安全并核实事实。"},reversed:{ko:"급격한 변화가 부담스럽다면 지금 조정할 수 있는 부분부터 나눠 보세요.",en:"If change feels overwhelming, break it into parts you can address now.",ja:"大きな変化が負担なら、今対処できる部分に分けて考えましょう。",zh:"如果变化令人不安，把它拆分成现在可以处理的部分。"},keywords:{ko:["점검","전환"],en:["reassessment","change"],ja:["見直し","転換"],zh:["审视","变化"]}},
  { id:"star",name:{ko:"별",en:"The Star",ja:"星",zh:"星星"},upright:{ko:"작은 회복과 희망의 단서를 살펴보세요. 꾸준한 돌봄이 다음 단계에 힘을 줍니다.",en:"Look for small signs of renewal. Consistent care can support your next step.",ja:"小さな回復や希望の兆しを見つけましょう。日々のケアが次の一歩を支えます。",zh:"留意细微的恢复与希望，坚持照顾自己能支持下一步。"},reversed:{ko:"기대가 흐릿하다면 당장 할 수 있는 구체적인 행동 하나를 정해 보세요.",en:"If hope feels distant, choose one concrete action you can take today.",ja:"希望が見えにくいときは、今日できる具体的な行動を一つ決めましょう。",zh:"如果希望显得遥远，先选一件今天能做的具体行动。"},keywords:{ko:["회복","희망"],en:["renewal","hope"],ja:["回復","希望"],zh:["恢复","希望"]}},
  { id:"moon",name:{ko:"달",en:"The Moon",ja:"月",zh:"月亮"},upright:{ko:"정보가 불분명할 수 있으니 추측을 사실로 여기지 말고 확인할 시간을 가지세요.",en:"Some details may be unclear. Avoid treating assumptions as facts and allow time to verify.",ja:"情報が曖昧なことも。推測を事実と決めつけず、確認する時間を取りましょう。",zh:"细节可能尚不清楚，不要把猜测当事实，留出核实时间。"},reversed:{ko:"혼란의 원인을 하나씩 확인하면 막연한 걱정을 줄이는 데 도움이 됩니다.",en:"Checking the source of uncertainty one piece at a time may ease vague worries.",ja:"不安の原因を一つずつ確かめると、漠然とした心配を整理しやすくなります。",zh:"逐项核实不确定之处，可能有助于缓解模糊的担忧。"},keywords:{ko:["불확실성","직감"],en:["uncertainty","intuition"],ja:["不確かさ","直感"],zh:["不确定","直觉"]}},
  { id:"sun",name:{ko:"태양",en:"The Sun",ja:"太陽",zh:"太阳"},upright:{ko:"잘된 점을 인정하고 기쁜 일을 주변과 나누면 활력을 이어가기 좋습니다.",en:"Recognize what is going well and share a positive moment with others.",ja:"うまくいっていることを認め、うれしい出来事を周りと分かち合いましょう。",zh:"认可进展顺利之处，并与身边的人分享愉快时刻。"},reversed:{ko:"작은 진전도 놓치지 말고 과한 기대는 현실적인 단계로 나눠 보세요.",en:"Notice small progress and break oversized expectations into realistic steps.",ja:"小さな前進を見逃さず、大きすぎる期待は現実的な段階に分けましょう。",zh:"留意细小进展，并把过高期待拆解为现实步骤。"},keywords:{ko:["활력","명료함"],en:["vitality","clarity"],ja:["活力","明快さ"],zh:["活力","清晰"]}},
  { id:"judgement",name:{ko:"심판",en:"Judgement",ja:"審判",zh:"审判"},upright:{ko:"지난 경험을 돌아보고 지금의 자신에게 맞는 다음 결정을 정리할 때입니다.",en:"Review past experience and clarify a next decision that fits who you are now.",ja:"これまでの経験を振り返り、今の自分に合う次の決断を整理しましょう。",zh:"回顾过往经验，梳理适合当下自己的下一步决定。"},reversed:{ko:"과거의 실수를 반복해서 탓하기보다 배운 점과 바꿀 행동을 구분해 보세요.",en:"Instead of replaying past mistakes, separate what you learned from what you can change.",ja:"過去の失敗を責め続けず、学んだことと変えられる行動を分けましょう。",zh:"与其反复责怪过去，不如区分收获与可改变的行动。"},keywords:{ko:["되돌아봄","결정"],en:["review","decision"],ja:["振り返り","決断"],zh:["回顾","决定"]}},
  { id:"world",name:{ko:"세계",en:"The World",ja:"世界",zh:"世界"},upright:{ko:"한 단계의 마무리를 확인하고 다음 목표를 향해 배운 것을 가져가세요.",en:"Acknowledge a completed stage and carry what you learned into the next goal.",ja:"一区切りを認め、学んだことを次の目標へ持っていきましょう。",zh:"确认一个阶段的完成，并把经验带入下一个目标。"},reversed:{ko:"마무리가 남아 있다면 범위를 작게 정해 끝낼 수 있는 부분부터 처리하세요.",en:"If something remains unfinished, define a manageable scope and complete one part.",ja:"未完了のことがあるなら、範囲を小さく決めて終えられる部分から進めましょう。",zh:"如果还有未完成之处，缩小范围并先完成一部分。"},keywords:{ko:["완성","다음 단계"],en:["completion","next step"],ja:["完成","次の段階"],zh:["完成","下一阶段"]}},
];
