import type { Locale } from "@/i18n/routing";

type Copy = { overview:string; steps:string[]; example:string; options:string; caution:string };
type LocalizedCopy = Record<Locale, Copy>;
const content: Record<string, LocalizedCopy> = {
  "lotto-number-generator": {
    ko:{overview:"중복 없이 6개 번호를 무작위로 조합해 로또 번호 추천을 받을 수 있습니다. 추첨 결과를 예측하거나 당첨을 보장하는 기능은 아닙니다.",steps:["번호 조합 개수를 선택합니다.","생성 버튼을 눌러 각 조합을 확인합니다.","원하는 조합을 복사하거나 다시 생성합니다."],example:"여러 번호 조합을 한 번에 만들어 구매 전에 목록을 비교할 수 있습니다.",options:"각 조합은 1부터 45 사이에서 중복 없이 구성됩니다.",caution:"무작위 번호는 당첨 확률을 높이지 않습니다. 구매와 참여는 본인의 책임과 한도 안에서 결정하세요."},
    en:{overview:"Generate one or five six-number 6/45 games. Choose numbers to include or exclude, set an odd/even ratio, and review recent combinations saved only in this browser. This random picker cannot predict a draw or guarantee a win.",steps:["Choose up to six included numbers and any numbers to exclude.","Select one or five games, then set an odd/even ratio if desired.","Generate, copy a game, or reuse a recent result."],example:"Save a few combinations in this browser and copy them when you are ready.",options:"Each game contains six distinct numbers from 1 to 45. Sorting changes display order only.",caution:"Random numbers do not improve the odds of winning. Participate responsibly and within your own limits."},
    ja:{overview:"重複しない6個の数字を組み合わせて、ロト番号を作成します。抽選結果の予測や当選を保証するものではありません。",steps:["作成する組み合わせ数を選びます。","生成して各組み合わせを確認します。","必要な組み合わせをコピーするか、再生成します。"],example:"複数の番号をまとめて作り、購入前に候補を見比べられます。",options:"各組み合わせは1から45までの数字から重複なしで選ばれます。",caution:"ランダムな番号で当選確率が上がるわけではありません。無理のない範囲でご利用ください。"},
    zh:{overview:"随机组合6个不重复号码，可用于生成彩票号码参考。本工具不会预测开奖结果，也不保证中奖。",steps:["选择要生成的组合数量。","点击生成并查看每组号码。","复制需要的组合，或重新生成。"],example:"一次生成多组号码，方便在使用前比较候选组合。",options:"每组从1至45中选出6个不重复号码。",caution:"随机号码不会提高中奖概率，请量力参与并自行承担责任。"},
  },
  "powerball-number-generator": {
    ko:{overview:"파워볼 공식 게임 방식에 맞춰 1~69 흰 공 5개와 1~26 Powerball 1개를 무작위로 추첨합니다. 파워볼 번호 생성기로도 이용할 수 있습니다.",steps:["한 게임 또는 다섯 게임을 선택합니다.","번호 추첨하기를 눌러 흰 공과 Powerball 결과를 확인합니다.","결과를 복사하거나 다시 추첨합니다."],example:"흰 공 번호는 오름차순으로 표시되고 Powerball은 별도 색상으로 구분됩니다.",options:"모든 번호는 브라우저에서 무작위로 생성되며 서버로 전송되지 않습니다.",caution:"오락 목적의 무작위 추첨 도구이며 당첨을 예측하거나 보장하지 않습니다. 실제 구매, 참가 가능 지역, 연령 및 세부 규칙은 공식 안내를 확인하세요."},
    en:{overview:"Generate five unique white balls from 1 to 69 and one Powerball from 1 to 26 using the current game matrix.",steps:["Choose one or five games.","Draw numbers to see the white balls and separate Powerball.","Copy the results or draw again."],example:"White balls are sorted in ascending order; the red Powerball is shown separately.",options:"Numbers are generated randomly in your browser and are not sent to a server.",caution:"For entertainment only. This tool cannot predict winning numbers or guarantee a prize. Check official guidance for purchase, eligible locations, age requirements, and rules."},
    ja:{overview:"現在の公式ルールに沿って、1～69から重複しない白いボールを5個、1～26からPowerballを1個抽選します。",steps:["1口または5口を選びます。","番号を抽選して白いボールとPowerballを確認します。","結果をコピーするか、もう一度抽選します。"],example:"白いボールは昇順で表示し、赤いPowerballは別に表示します。",options:"番号はブラウザー内でランダムに生成され、サーバーには送信されません。",caution:"娯楽目的のツールです。当選番号の予測や当選の保証はできません。購入方法、販売地域、年齢制限、詳細なルールは公式案内をご確認ください。"},
    zh:{overview:"按照当前官方规则，从1至69中随机抽取5个不重复白球，并从1至26中抽取1个Powerball。",steps:["选择抽取一注或五注。","点击抽取号码，查看白球和单独显示的Powerball。","复制结果或再次抽取。"],example:"白球号码按升序排列，红色Powerball单独显示。",options:"号码在浏览器中随机生成，不会发送到服务器。",caution:"本工具仅供娱乐，不会预测中奖号码或保证中奖。购票方式、可参与地区、年龄要求及详细规则请查看官方说明。"},
  },
  "mega-millions-number-generator": {
    ko:{overview:"Mega Millions 현재 공식 규칙에 맞춰 1~70 메인 번호 5개와 1~24 Mega Ball 1개를 무작위로 추첨합니다. 메가밀리언 번호 생성기로도 이용할 수 있습니다.",steps:["한 게임 또는 다섯 게임을 선택합니다.","번호 추첨하기를 눌러 메인 번호와 Mega Ball 결과를 확인합니다.","결과를 복사하거나 다시 추첨합니다."],example:"메인 번호는 오름차순으로 표시되고 Mega Ball은 별도 색상으로 구분됩니다.",options:"모든 번호는 브라우저에서 무작위로 생성되며 서버로 전송되지 않습니다.",caution:"오락 목적의 무작위 추첨 도구이며 당첨을 예측하거나 보장하지 않습니다. 실제 구매, 참가 가능 지역, 연령 및 세부 규칙은 공식 안내를 확인하세요."},
    en:{overview:"Generate five unique main numbers from 1 to 70 and one Mega Ball from 1 to 24 under the current game rules.",steps:["Choose one or five games.","Draw numbers to see the main numbers and separate Mega Ball.","Copy the results or draw again."],example:"Main numbers are sorted in ascending order; the gold Mega Ball is shown separately.",options:"Numbers are generated randomly in your browser and are not sent to a server.",caution:"For entertainment only. This tool cannot predict winning numbers or guarantee a prize. Check official guidance for purchase, eligible locations, age requirements, and rules."},
    ja:{overview:"現在の公式ルールに沿って、1～70から重複しない数字を5個、1～24からMega Ballを1個抽選します。",steps:["1口または5口を選びます。","番号を抽選してメイン数字とMega Ballを確認します。","結果をコピーするか、もう一度抽選します。"],example:"メイン数字は昇順で表示し、金色のMega Ballは別に表示します。",options:"番号はブラウザー内でランダムに生成され、サーバーには送信されません。",caution:"娯楽目的のツールです。当選番号の予測や当選の保証はできません。購入方法、販売地域、年齢制限、詳細なルールは公式案内をご確認ください。"},
    zh:{overview:"按照当前官方规则，从1至70中随机抽取5个不重复主号码，并从1至24中抽取1个Mega Ball。",steps:["选择抽取一注或五注。","点击抽取号码，查看主号码和单独显示的Mega Ball。","复制结果或再次抽取。"],example:"主号码按升序排列，金色Mega Ball单独显示。",options:"号码在浏览器中随机生成，不会发送到服务器。",caution:"本工具仅供娱乐，不会预测中奖号码或保证中奖。购票方式、可参与地区、年龄要求及详细规则请查看官方说明。"},
  },
  "japan-loto6-number-generator": {
    ko:{overview:"일본 LOTO 6는 1부터 43까지의 숫자 중 서로 다른 6개를 선택하는 숫자선택형 복권입니다. 이 도구는 공식 규칙에 맞춰 번호를 무작위로 추첨합니다.",steps:["한 게임 또는 다섯 게임을 선택합니다.","번호 추첨하기를 눌러 각 조합을 확인합니다.","결과를 전체 또는 개별 복사하거나 다시 추첨합니다."],example:"각 조합에는 1~43 사이의 서로 다른 번호 6개가 오름차순으로 표시됩니다.",options:"번호는 브라우저에서 무작위로 생성되며 보너스 번호는 임의로 추가하지 않습니다.",caution:"이 도구는 무작위 번호 추첨을 위한 도구이며 당첨 번호를 예측하거나 당첨을 보장하지 않습니다. 구매 방법, 판매 지역, 판매 조건, 추첨 일정 및 최신 규칙은 일본 공식 복권 안내를 확인하세요."},
    en:{overview:"Japan LOTO 6 is a number selection lottery in which players choose six different numbers from 1 to 43. This tool draws random combinations using those rules.",steps:["Choose one or five games.","Draw numbers to view each combination.","Copy all results or an individual game, or draw again."],example:"Each game shows six distinct numbers from 1 to 43 in ascending order.",options:"Numbers are generated in your browser. No bonus number is added.",caution:"This tool draws random numbers for entertainment. It cannot predict winning numbers or guarantee a prize. Check Japan's official lottery guidance for purchase methods, sales regions and conditions, draw schedules, and current rules."},
    ja:{overview:"ロト6は、1から43までの数字から異なる6個を選ぶ数字選択式宝くじです。このツールでは、そのルールに沿った番号をランダムに抽選します。",steps:["1口または5口を選びます。","番号を抽選して各組み合わせを確認します。","すべてまたは個別にコピーするか、もう一度抽選します。"],example:"各組み合わせには1～43の異なる数字が6個、昇順で表示されます。",options:"番号はブラウザー内で生成し、ボーナス数字は追加しません。",caution:"娯楽目的の番号抽選ツールです。当せん番号の予測や当せんの保証はできません。購入方法、販売地域・条件、抽せん日、最新ルールは宝くじ公式サイトをご確認ください。"},
    zh:{overview:"日本LOTO 6是一种数字选择型彩票，需从1至43中选择6个不同号码。本工具按照该规则随机抽取号码。",steps:["选择抽取一注或五注。","点击抽取号码并查看每组结果。","复制全部或单注结果，也可以再次抽取。"],example:"每组显示从1至43中抽取的6个不重复号码，并按升序排列。",options:"号码在浏览器中生成，不会额外添加奖金号码。",caution:"本工具仅供娱乐，随机抽取号码，不会预测中奖或保证中奖。购票方式、销售地区与条件、开奖日程及最新规则请查看日本官方彩票说明。"},
  },
  "japan-loto7-number-generator": {
    ko:{overview:"일본 LOTO 7은 1부터 37까지의 숫자 중 서로 다른 7개를 선택하는 숫자선택형 복권입니다. 이 도구는 공식 규칙에 맞춰 번호를 무작위로 추첨합니다.",steps:["한 게임 또는 다섯 게임을 선택합니다.","번호 추첨하기를 눌러 각 조합을 확인합니다.","결과를 전체 또는 개별 복사하거나 다시 추첨합니다."],example:"각 조합에는 1~37 사이의 서로 다른 번호 7개가 오름차순으로 표시됩니다.",options:"번호는 브라우저에서 무작위로 생성되며 보너스 번호는 임의로 추가하지 않습니다.",caution:"이 도구는 무작위 번호 추첨을 위한 도구이며 당첨 번호를 예측하거나 당첨을 보장하지 않습니다. 구매 방법, 판매 지역, 판매 조건, 추첨 일정 및 최신 규칙은 일본 공식 복권 안내를 확인하세요."},
    en:{overview:"Japan LOTO 7 is a number selection lottery in which players choose seven different numbers from 1 to 37. This tool draws random combinations using those rules.",steps:["Choose one or five games.","Draw numbers to view each combination.","Copy all results or an individual game, or draw again."],example:"Each game shows seven distinct numbers from 1 to 37 in ascending order.",options:"Numbers are generated in your browser. No bonus number is added.",caution:"This tool draws random numbers for entertainment. It cannot predict winning numbers or guarantee a prize. Check Japan's official lottery guidance for purchase methods, sales regions and conditions, draw schedules, and current rules."},
    ja:{overview:"ロト7は、1から37までの数字から異なる7個を選ぶ数字選択式宝くじです。このツールでは、そのルールに沿った番号をランダムに抽選します。",steps:["1口または5口を選びます。","番号を抽選して各組み合わせを確認します。","すべてまたは個別にコピーするか、もう一度抽選します。"],example:"各組み合わせには1～37の異なる数字が7個、昇順で表示されます。",options:"番号はブラウザー内で生成し、ボーナス数字は追加しません。",caution:"娯楽目的の番号抽選ツールです。当せん番号の予測や当せんの保証はできません。購入方法、販売地域・条件、抽せん日、最新ルールは宝くじ公式サイトをご確認ください。"},
    zh:{overview:"日本LOTO 7是一种数字选择型彩票，需从1至37中选择7个不同号码。本工具按照该规则随机抽取号码。",steps:["选择抽取一注或五注。","点击抽取号码并查看每组结果。","复制全部或单注结果，也可以再次抽取。"],example:"每组显示从1至37中抽取的7个不重复号码，并按升序排列。",options:"号码在浏览器中生成，不会额外添加奖金号码。",caution:"本工具仅供娱乐，随机抽取号码，不会预测中奖或保证中奖。购票方式、销售地区与条件、开奖日程及最新规则请查看日本官方彩票说明。"},
  },
  "japan-mini-loto-number-generator": {
    ko:{overview:"일본 MINI LOTO(미니로또)는 1부터 31까지의 숫자 중 서로 다른 5개를 선택하는 숫자선택형 복권입니다. 이 도구는 공식 규칙에 맞춰 번호를 무작위로 추첨합니다.",steps:["한 게임 또는 다섯 게임을 선택합니다.","번호 추첨하기를 눌러 각 조합을 확인합니다.","결과를 전체 또는 개별 복사하거나 다시 추첨합니다."],example:"각 조합에는 1~31 사이의 서로 다른 번호 5개가 오름차순으로 표시됩니다.",options:"번호는 브라우저에서 무작위로 생성되며 보너스 번호는 임의로 추가하지 않습니다.",caution:"이 도구는 무작위 번호 추첨을 위한 도구이며 당첨 번호를 예측하거나 당첨을 보장하지 않습니다. 구매 방법, 판매 지역, 판매 조건, 추첨 일정 및 최신 규칙은 일본 공식 복권 안내를 확인하세요."},
    en:{overview:"Japan Mini Loto is a number selection lottery in which players choose five different numbers from 1 to 31. This tool draws random combinations using those rules.",steps:["Choose one or five games.","Draw numbers to view each combination.","Copy all results or an individual game, or draw again."],example:"Each game shows five distinct numbers from 1 to 31 in ascending order.",options:"Numbers are generated in your browser. No bonus number is added.",caution:"This tool draws random numbers for entertainment. It cannot predict winning numbers or guarantee a prize. Check Japan's official lottery guidance for purchase methods, sales regions and conditions, draw schedules, and current rules."},
    ja:{overview:"ミニロトは、1から31までの数字から異なる5個を選ぶ数字選択式宝くじです。このツールでは、そのルールに沿った番号をランダムに抽選します。",steps:["1口または5口を選びます。","番号を抽選して各組み合わせを確認します。","すべてまたは個別にコピーするか、もう一度抽選します。"],example:"各組み合わせには1～31の異なる数字が5個、昇順で表示されます。",options:"番号はブラウザー内で生成し、ボーナス数字は追加しません。",caution:"娯楽目的の番号抽選ツールです。当せん番号の予測や当せんの保証はできません。購入方法、販売地域・条件、抽せん日、最新ルールは宝くじ公式サイトをご確認ください。"},
    zh:{overview:"日本Mini Loto是一种数字选择型彩票，需从1至31中选择5个不同号码。本工具按照该规则随机抽取号码。",steps:["选择抽取一注或五注。","点击抽取号码并查看每组结果。","复制全部或单注结果，也可以再次抽取。"],example:"每组显示从1至31中抽取的5个不重复号码，并按升序排列。",options:"号码在浏览器中生成，不会额外添加奖金号码。",caution:"本工具仅供娱乐，随机抽取号码，不会预测中奖或保证中奖。购票方式、销售地区与条件、开奖日程及最新规则请查看日本官方彩票说明。"},
  },
  "random-wheel": {
    ko:{overview:"온라인 룰렛에 메뉴나 이름을 입력해 점심 메뉴, 발표 순서, 당번처럼 하나를 고를 수 있습니다.",steps:["항목을 한 줄에 하나씩 입력합니다.","룰렛 돌리기를 눌러 결과를 확인합니다.","필요하면 당첨 항목을 제외하고 다시 돌립니다."],example:"점심 메뉴 후보를 적어 오늘 뭐 먹지 고민을 줄이거나, 모임에서 순서를 정할 수 있습니다.",options:"빈 항목은 선택 후보에서 제외됩니다. 당첨 항목 제거 여부를 선택할 수 있습니다.",caution:"룰렛은 입력된 항목 중 하나를 무작위로 고릅니다. 항목을 중복 입력하면 해당 항목의 선택 비중이 커집니다."},
    en:{overview:"Add choices to a wheel and see each entry printed inside its matching sector. Use it for lunch, presentation order, or other group decisions.",steps:["Enter one option per line.","Review each labeled sector and spin the wheel.","Optionally remove the winner before spinning again."],example:"List lunch choices when the group cannot decide what to eat, or use the wheel to assign a turn.",options:"Blank lines are ignored, duplicate entries are optional, and you can remove a selected winner from later spins.",caution:"The wheel selects from the options you provide. Repeating an option gives it a larger share of the choices."},
    ja:{overview:"候補を入力してオンラインルーレットを回し、ランチ、発表順、当番などを選べます。",steps:["候補を1行に1つ入力します。","ルーレットを回して結果を確認します。","必要に応じて当選項目を外して再度回します。"],example:"ランチの候補から今日のメニューを選んだり、集まりの順番を決めたりできます。",options:"空行は候補から除外されます。当選項目を次回から外すこともできます。",caution:"入力された候補からランダムに選びます。同じ候補を複数入力すると、その分選ばれやすくなります。"},
    zh:{overview:"输入候选项并转动在线转盘，可用于选择午餐、发言顺序、值日安排等。",steps:["每行输入一个候选项。","点击转动转盘并查看结果。","可选择移除已选项后再次抽取。"],example:"列出午餐菜单来决定今天吃什么，也可以用来安排活动顺序。",options:"空行不会参与抽取，也可以设置抽中后移除该项。",caution:"转盘只会从输入的候选项中选择。重复输入同一项会增加它被选中的机会。"},
  },
  "ladder-game": {
    ko:{overview:"참가자와 결과를 연결하는 온라인 사다리타기로 당첨자나 역할을 무작위 배정합니다.",steps:["참가자와 결과를 같은 개수로 입력합니다.","사다리를 생성한 뒤 참가자를 선택합니다.","경로를 따라 연결된 결과를 확인합니다."],example:"친구 이름과 메뉴·벌칙·상품을 각각 입력해 공정한 사다리 추첨을 할 수 있습니다.",options:"참가자와 결과는 한 줄에 하나씩 입력하며 빈 줄은 제외됩니다.",caution:"사다리 경로는 결과를 보기 전에 무작위로 생성됩니다. 중요한 결정에는 별도의 확인 절차를 두세요."},
    en:{overview:"Create a randomized ladder that connects participants to outcomes for a casual draw or role assignment.",steps:["Enter equal numbers of participants and outcomes, one per line.","Generate the ladder and choose a participant.","Follow the path to see the matched outcome."],example:"Pair a list of friends with menu choices, prizes, or lighthearted tasks.",options:"Participants and outcomes are entered on separate lines; blank lines are skipped.",caution:"The ladder is randomized before results are shown. Use an independent review for decisions with real consequences."},
    ja:{overview:"参加者と結果をつなぐオンラインあみだくじを作り、当選者や役割をランダムに決めます。",steps:["参加者と結果を同じ数だけ1行ずつ入力します。","あみだくじを作成し、参加者を選びます。","線をたどって対応する結果を確認します。"],example:"友人の名前とメニュー・景品・担当を入力して、気軽な抽選に使えます。",options:"参加者と結果はそれぞれ1行ずつ入力し、空行は除外されます。",caution:"結果を表示する前に経路をランダムに作成します。重要な決定では別途確認してください。"},
    zh:{overview:"生成连接参与者与结果的随机梯子，可用于抽奖或分配轻松的任务。",steps:["分别输入数量相同的参与者和结果，每行一项。","生成梯子并选择一位参与者。","沿路径查看对应结果。"],example:"把朋友名单与菜单、奖品或趣味任务配对进行抽选。",options:"参与者和结果分别逐行输入，空行会自动忽略。",caution:"结果展示前会先随机生成梯子路径。涉及重要事项时请另外核实。"},
  },
  "random-number": {
    ko:{overview:"최소값과 최대값 사이에서 필요한 개수만큼 랜덤 숫자를 뽑습니다. 번호 추첨이나 간단한 무작위 선택에 쓸 수 있습니다.",steps:["최솟값과 최댓값을 입력합니다.","뽑을 숫자 개수와 중복 허용 여부를 정합니다.","생성 결과를 복사하거나 다시 뽑습니다."],example:"1~45에서 6개 숫자를 뽑거나 발표 순번 하나를 무작위로 정할 수 있습니다.",options:"중복 금지와 오름차순 정렬을 선택할 수 있습니다.",caution:"중복을 허용하지 않을 때는 요청 개수가 범위 안의 숫자 개수를 넘을 수 없습니다."},
    en:{overview:"Draw a chosen number of random values between a minimum and maximum for quick picks, games, or sampling.",steps:["Enter the lower and upper bounds.","Set the draw count and whether repeats are allowed.","Copy the result or draw again."],example:"Pick six values from 1 to 45, or choose a random number for a turn order.",options:"Choose whether to allow duplicates and sort the output.",caution:"Without repeats, the requested count cannot exceed the number of available values."},
    ja:{overview:"最小値から最大値の範囲で、必要な個数の数字をランダムに抽選します。番号選びや簡単な抽選に使えます。",steps:["最小値と最大値を入力します。","抽選数と重複の可否を設定します。","結果をコピーするか、引き直します。"],example:"1～45から6個選んだり、順番を決める数字を一つ選んだりできます。",options:"重複の有無や結果の昇順表示を選べます。",caution:"重複なしの場合、抽選数は範囲内の数字の個数を超えられません。"},
    zh:{overview:"在最小值和最大值之间随机抽取指定数量的数字，可用于号码抽选或简单随机选择。",steps:["输入最小值和最大值。","设置抽取数量以及是否允许重复。","复制结果或重新抽取。"],example:"从1到45中抽取6个数字，或随机决定一个活动顺序号。",options:"可以设置是否允许重复，并选择是否按升序排列。",caution:"不允许重复时，抽取数量不能超过范围内可用数字的总数。"},
  },
  timer: {
    ko:{overview:"온라인 타이머로 요리, 공부, 운동처럼 정해진 시간이 필요한 작업의 남은 시간을 확인하세요.",steps:["시·분·초를 입력합니다.","시작을 누르고 필요하면 일시정지합니다.","완료 알림을 확인한 뒤 초기화하거나 다시 설정합니다."],example:"집중 작업을 25분으로 맞추거나 짧은 휴식 시간을 설정할 수 있습니다.",options:"시간을 설정한 뒤 시작·일시정지·계속·초기화를 사용할 수 있습니다.",caution:"브라우저 탭이나 기기의 절전 상태에 따라 알림음 재생이 제한될 수 있으므로 중요한 일정은 별도 시계를 함께 사용하세요."},
    en:{overview:"Use this online countdown timer to track a set duration for cooking, study, exercise, or a short break.",steps:["Set hours, minutes, and seconds.","Start the timer and pause or resume as needed.","When it ends, reset it or enter another duration."],example:"Set a focused work interval or a brief break between tasks.",options:"The timer supports start, pause, resume, and reset controls.",caution:"Browser or device power settings can affect audio alerts. Use a separate alarm for critical deadlines."},
    ja:{overview:"料理、勉強、運動など、決まった時間を測りたいときに使えるオンラインタイマーです。",steps:["時・分・秒を設定します。","開始し、必要に応じて一時停止します。","終了を確認し、リセットまたは再設定します。"],example:"集中する時間や短い休憩時間を設定できます。",options:"開始・一時停止・再開・リセットに対応しています。",caution:"ブラウザーや端末の省電力設定によって音が鳴らない場合があります。重要な予定には別のアラームもご利用ください。"},
    zh:{overview:"使用在线倒计时记录烹饪、学习、运动或休息等需要限定时长的任务。",steps:["设置小时、分钟和秒。","启动计时器，并按需暂停或继续。","结束后重置或输入新的时长。"],example:"设置一段专注时间，或安排任务之间的短暂休息。",options:"支持开始、暂停、继续和重置。",caution:"浏览器标签页或设备省电设置可能影响提示音。重要截止时间请同时使用其他闹钟。"},
  },
  "password-generator": {
    ko:{overview:"브라우저에서 Web Crypto 기반 난수로 새 비밀번호를 생성합니다. 사이트마다 다른 비밀번호를 만들 때 활용하세요.",steps:["원하는 길이를 설정합니다.","포함할 문자 종류와 유사 문자 제외 옵션을 선택합니다.","생성한 비밀번호를 복사해 안전한 곳에 보관합니다."],example:"계정별로 별도의 긴 비밀번호를 만든 뒤 비밀번호 관리자에 저장할 수 있습니다.",options:"대문자·소문자·숫자·특수문자와 길이를 조정할 수 있습니다.",caution:"생성 결과는 이 화면에서만 표시됩니다. 공유 컴퓨터에서는 복사 기록과 화면을 지우고, 사이트의 비밀번호 정책을 확인하세요."},
    en:{overview:"Generate a new password in your browser using Web Crypto randomness. Create a different password for each account.",steps:["Choose a password length.","Select character groups and whether to avoid look-alike characters.","Copy the result and store it securely."],example:"Create a long, unique password for an account and save it in a password manager.",options:"Adjust length, uppercase and lowercase letters, numbers, symbols, and ambiguous characters.",caution:"The generated value is shown on this device. Clear the screen and clipboard on shared devices, and check the site's password rules."},
    ja:{overview:"Web Cryptoの乱数を使い、ブラウザー内で新しいパスワードを作成します。サービスごとに別の文字列を用意できます。",steps:["パスワードの長さを決めます。","使う文字種と、似た文字を除外するか選びます。","生成結果をコピーして安全に保管します。"],example:"アカウントごとに長いパスワードを作り、パスワード管理ツールに保存できます。",options:"長さ、大文字・小文字・数字・記号、紛らわしい文字の除外を設定できます。",caution:"結果はこの端末に表示されます。共有端末では画面やクリップボードを消し、利用先の条件も確認してください。"},
    zh:{overview:"使用Web Crypto随机数在浏览器中生成新密码。为不同账户设置不同密码。",steps:["选择密码长度。","选择字符种类，并决定是否排除易混淆字符。","复制结果并妥善保管。"],example:"为账户生成较长且独立的密码，并保存到密码管理器中。",options:"可调整长度、大写字母、小写字母、数字、符号和易混淆字符。",caution:"结果仅显示在当前设备上。在公用设备上请清除屏幕与剪贴板内容，并确认目标网站的密码规则。"},
  },
  "wifi-qr": {
    ko:{overview:"Wi-Fi 이름과 보안 정보를 담은 QR 코드를 만들어 손님이 네트워크에 쉽게 연결하도록 할 수 있습니다.",steps:["SSID와 보안 방식, 비밀번호를 입력합니다.","숨김 네트워크라면 해당 옵션을 선택합니다.","QR을 화면에 보여 주거나 기기에 저장합니다."],example:"가정이나 매장 방문객이 비밀번호를 직접 입력하지 않고 Wi-Fi에 연결할 수 있습니다.",options:"WPA/WPA2, WEP, 보안 없음, 숨김 네트워크를 설정할 수 있습니다.",caution:"QR 코드를 스캔할 수 있는 사람은 네트워크에 접속할 수 있습니다. 공개 장소에 둘 때는 게스트 네트워크를 사용하세요."},
    en:{overview:"Create a Wi-Fi QR code with network details so guests can join without typing the password manually.",steps:["Enter the SSID, security type, and password.","Choose the hidden-network option if needed.","Display the QR code or save it to your device."],example:"Let visitors connect to a home or business guest network by scanning a code.",options:"Choose WPA/WPA2, WEP, no security, and whether the network is hidden.",caution:"Anyone who can scan the code may be able to join. Use a guest network before displaying it publicly."},
    ja:{overview:"Wi-Fi情報を含むQRコードを作成し、来客がパスワードを手入力せずに接続できるようにします。",steps:["SSID、セキュリティ方式、パスワードを入力します。","必要ならステルス設定を選びます。","QRコードを表示または端末に保存します。"],example:"自宅や店舗のゲスト用Wi-Fiへの接続案内に使えます。",options:"WPA/WPA2、WEP、暗号化なし、非公開ネットワークを設定できます。",caution:"QRコードを読み取れる人は接続できる可能性があります。掲示する場合はゲストネットワークを利用してください。"},
    zh:{overview:"生成包含Wi-Fi信息的二维码，方便访客扫码连接，无需手动输入密码。",steps:["输入SSID、安全类型和密码。","如有需要，选择隐藏网络。","展示二维码或保存到设备。"],example:"可用于家庭或店铺访客网络的连接说明。",options:"支持WPA/WPA2、WEP、无加密以及隐藏网络选项。",caution:"能够扫描二维码的人可能可以接入网络。公开展示前建议使用访客网络。"},
  },
  "image-compress": {
    ko:{overview:"이미지 압축으로 사진의 픽셀 크기를 유지하면서 파일 용량을 줄여 업로드나 공유를 준비할 수 있습니다.",steps:["이미지를 선택하거나 끌어 놓습니다.","압축 품질을 조정합니다.","미리 확인하고 결과 이미지를 다운로드합니다."],example:"웹사이트 첨부나 이메일 전송 전에 큰 사진의 파일 크기를 줄일 수 있습니다.",options:"품질 슬라이더로 결과 용량과 시각적 품질의 균형을 조절합니다.",caution:"압축 결과는 이미지 내용과 파일 형식에 따라 다릅니다. 원본은 그대로 유지되므로 다운로드한 결과를 확인하세요."},
    en:{overview:"Reduce an image's file size while keeping its pixel dimensions, making it easier to upload or share.",steps:["Select or drop an image.","Adjust the compression quality.","Preview and download the compressed result."],example:"Shrink a large photo before attaching it to a website form or email.",options:"Use the quality control to balance output size and visual detail.",caution:"Compression varies by image and format. The original remains unchanged; review the downloaded result."},
    ja:{overview:"画像のピクセル寸法を保ちながらファイル容量を抑え、アップロードや共有に備えます。",steps:["画像を選択またはドラッグします。","圧縮品質を調整します。","結果を確認してダウンロードします。"],example:"Webフォームやメールに添付する前に、大きな写真の容量を減らせます。",options:"品質スライダーで容量と見た目のバランスを調整できます。",caution:"圧縮結果は画像や形式によって異なります。元画像は変更されないため、保存結果をご確認ください。"},
    zh:{overview:"在保持图像像素尺寸的同时压缩文件体积，方便上传或分享。",steps:["选择或拖入图像。","调整压缩质量。","预览并下载压缩结果。"],example:"在上传网页或通过邮件发送前，缩小较大的照片文件。",options:"通过质量设置平衡文件大小与图像细节。",caution:"压缩效果因图像内容和格式而异。原图不会修改，请检查下载后的结果。"},
  },
  "image-resize": {
    ko:{overview:"이미지 가로·세로 픽셀을 바꿔 프로필, 문서, 웹 게시에 맞는 크기로 조정합니다.",steps:["이미지를 선택합니다.","원하는 가로·세로 픽셀을 입력합니다.","비율 유지 여부를 확인하고 변환 결과를 저장합니다."],example:"가로 1200px 사진을 게시용 800px 이미지로 줄이거나 정해진 배너 크기로 맞출 수 있습니다.",options:"가로·세로를 지정하고 원본 비율 고정을 켜거나 끌 수 있습니다.",caution:"확대하면 선명도가 낮아질 수 있습니다. 인쇄 크기와 픽셀 해상도는 서로 다른 값입니다."},
    en:{overview:"Change image width and height in pixels to fit a profile, document, website, or other target size.",steps:["Choose an image.","Enter the target width and height in pixels.","Set whether to keep the aspect ratio, then save the result."],example:"Resize a 1200-pixel photo to 800 pixels for a web post, or match a banner size.",options:"Set width and height, with an option to preserve the original aspect ratio.",caution:"Upscaling can reduce sharpness. Pixel dimensions do not by themselves define print size."},
    ja:{overview:"画像の幅と高さをピクセル単位で変更し、プロフィール、書類、Web掲載などに合わせます。",steps:["画像を選択します。","目標の幅と高さを入力します。","縦横比を維持するか選び、結果を保存します。"],example:"横幅1200pxの写真をWeb掲載用に800pxへ縮小したり、バナー寸法に合わせたりできます。",options:"幅・高さを指定し、元の縦横比を固定するか選べます。",caution:"拡大すると鮮明さが低下することがあります。ピクセル寸法だけでは印刷サイズは決まりません。"},
    zh:{overview:"调整图像的像素宽高，以适配头像、文档、网页发布等用途。",steps:["选择一张图像。","输入目标宽度和高度（像素）。","选择是否保持原始比例，然后保存结果。"],example:"将宽1200像素的照片缩小到800像素用于网页，或调整到指定横幅尺寸。",options:"可设置宽度和高度，并选择保持原始宽高比。",caution:"放大可能降低清晰度。像素尺寸本身并不等于打印尺寸。"},
  },
  "pdf-merge": {
    ko:{overview:"여러 PDF 파일을 원하는 순서대로 하나의 문서로 합쳐 제출·공유·보관을 간편하게 합니다.",steps:["합칠 PDF를 선택합니다.","파일 목록의 순서를 확인합니다.","병합을 실행하고 새 PDF를 다운로드합니다."],example:"계약서의 부속 문서나 여러 장의 스캔 PDF를 하나의 파일로 묶을 수 있습니다.",options:"선택한 파일 순서대로 페이지가 연결됩니다.",caution:"암호화되었거나 손상된 PDF는 처리되지 않을 수 있습니다. 결과 페이지 순서와 내용을 열어 확인하세요."},
    en:{overview:"Combine multiple PDF files in the order you choose into one document for sharing, submission, or archiving.",steps:["Select the PDFs to combine.","Review the order in the file list.","Merge and download the new PDF."],example:"Join scanned pages or supporting documents into a single file for a submission.",options:"Pages are appended in the order of the selected files.",caution:"Encrypted or damaged PDFs may not process. Open the result and verify its page order and contents."},
    ja:{overview:"複数のPDFを指定順に一つの文書へまとめ、提出・共有・保管をしやすくします。",steps:["結合するPDFを選択します。","ファイル一覧で順序を確認します。","結合して新しいPDFをダウンロードします。"],example:"契約書の添付資料や複数のスキャンPDFを一つにまとめられます。",options:"選択したファイルの順にページが連結されます。",caution:"暗号化または破損したPDFは処理できない場合があります。結果のページ順と内容をご確認ください。"},
    zh:{overview:"按指定顺序合并多个PDF，便于提交、分享或归档为一个文档。",steps:["选择要合并的PDF文件。","检查文件列表中的顺序。","执行合并并下载新PDF。"],example:"可将合同附件或多份扫描PDF合并成一个文件提交。",options:"页面会按照所选文件的顺序依次连接。",caution:"加密或损坏的PDF可能无法处理。请打开结果检查页序和内容。"},
  },
  "pdf-split": {
    ko:{overview:"PDF에서 필요한 페이지나 페이지 범위를 추출해 별도의 문서로 저장합니다.",steps:["PDF를 선택합니다.","추출할 페이지 번호나 범위를 입력합니다.","분할을 실행하고 새 PDF를 확인합니다."],example:"전체 자료 중 회의에 필요한 2~4쪽만 별도 파일로 만들 수 있습니다.",options:"페이지 번호와 범위는 화면에 안내된 쉼표·하이픈 형식으로 입력합니다.",caution:"페이지 번호는 원본 PDF의 순서를 기준으로 합니다. 처리 전에 입력한 번호를 다시 확인하세요."},
    en:{overview:"Extract selected pages or page ranges from a PDF and save them as a separate document.",steps:["Choose a PDF.","Enter the page numbers or ranges to extract.","Run the split and review the new PDF."],example:"Save pages 2–4 from a longer document as a separate file for a meeting.",options:"Enter page numbers and ranges using the comma and hyphen format shown in the tool.",caution:"Page numbers refer to the original PDF order. Double-check the range before processing."},
    ja:{overview:"PDFから必要なページや範囲を抽出し、別の文書として保存します。",steps:["PDFを選択します。","抽出するページ番号や範囲を入力します。","分割を実行し、新しいPDFを確認します。"],example:"長い資料から会議に必要な2～4ページだけを別ファイルにできます。",options:"画面の案内に従い、カンマとハイフンでページ番号や範囲を指定します。",caution:"ページ番号は元のPDFの順番に基づきます。処理前に指定範囲を確認してください。"},
    zh:{overview:"从PDF中提取指定页面或页码范围，并保存为单独文档。",steps:["选择一个PDF文件。","输入要提取的页码或范围。","执行拆分并检查新PDF。"],example:"可从长文档中单独导出会议所需的第2至4页。",options:"按照工具提示使用逗号和连字符输入页码与范围。",caution:"页码以原PDF顺序为准。处理前请再次确认输入范围。"},
  },
  "character-count": {
    ko:{overview:"글자수 세기로 공백 포함·제외 문자 수, 단어 수, 줄 수를 확인해 글자 제한을 점검합니다.",steps:["텍스트를 입력하거나 붙여 넣습니다.","실시간으로 표시되는 문자·단어·줄 수를 확인합니다.","필요하면 문장을 수정하고 다시 확인합니다."],example:"자기소개서 글자 제한이나 SNS 게시물 분량을 공백 제외 기준과 함께 확인할 수 있습니다.",options:"공백 포함 문자 수와 공백 제외 문자 수를 나누어 확인할 수 있습니다.",caution:"서비스마다 글자 수 산정 방식이 다를 수 있습니다. 제출처에서 안내한 기준을 최종 확인하세요."},
    en:{overview:"Count characters with and without spaces, words, and lines to check a text limit before submission.",steps:["Type or paste your text.","Review the live character, word, and line counts.","Edit the text and check the counts again."],example:"Check an application response against a character limit or estimate a social post's length.",options:"Compare character totals including spaces and excluding spaces.",caution:"Different services may count characters differently. Confirm the target platform's own rules before submitting."},
    ja:{overview:"文字数、空白を除いた文字数、単語数、行数を確認し、投稿や提出文の制限をチェックします。",steps:["文章を入力または貼り付けます。","文字数・単語数・行数を確認します。","必要に応じて文章を調整し、再確認します。"],example:"応募文の文字数制限やSNS投稿の長さを、空白を含む場合と除く場合で確認できます。",options:"空白を含む文字数と除外した文字数を比較できます。",caution:"サービスによって数え方が異なる場合があります。提出先の基準もご確認ください。"},
    zh:{overview:"统计字符数（含空格与不含空格）、单词数和行数，方便检查文本长度限制。",steps:["输入或粘贴文本。","查看实时字符数、单词数和行数。","修改文本后再次检查。"],example:"检查申请材料是否符合字数限制，或估算社交媒体帖子的长度。",options:"可分别查看包含空格和不包含空格的字符数。",caution:"不同服务的字符统计规则可能不同。提交前请确认目标平台的要求。"},
  },
  "json-formatter": {
    ko:{overview:"JSON Formatter는 JSON 구조를 들여쓰기해 읽기 쉽게 정리하거나 압축해 한 줄로 만듭니다.",steps:["JSON 텍스트를 입력합니다.","정렬 또는 Minify를 선택합니다.","오류가 표시되면 문법을 수정하고 결과를 복사합니다."],example:"API 응답 JSON의 중첩 객체와 배열을 정리해 구조를 빠르게 살펴볼 수 있습니다.",options:"Pretty Print는 가독성을 높이고 Minify는 불필요한 공백을 줄입니다.",caution:"이 도구는 형식을 정리하며 JSON을 실행하거나 외부로 전송하지 않습니다. 민감한 값은 화면 공유 전에 가리세요."},
    en:{overview:"Format JSON with indentation for readability or minify it into a compact string.",steps:["Enter JSON text.","Choose Pretty Print or Minify.","Fix any syntax error shown, then copy the result."],example:"Reformat a nested API response to inspect objects and arrays more easily.",options:"Pretty Print adds readable spacing; Minify removes unnecessary whitespace.",caution:"This tool formats data; it does not execute or send JSON elsewhere. Hide sensitive values before sharing your screen."},
    ja:{overview:"JSON Formatterは、JSONをインデントして読みやすく整形したり、空白を減らして圧縮したりできます。",steps:["JSONテキストを入力します。","整形またはMinifyを選択します。","エラーが表示されたら構文を直し、結果をコピーします。"],example:"APIレスポンスの入れ子になったオブジェクトや配列を見やすく確認できます。",options:"整形は可読性を高め、Minifyは不要な空白を削除します。",caution:"JSONを実行したり外部送信したりせず、形式だけを処理します。画面共有前に機密値を隠してください。"},
    zh:{overview:"JSON格式化工具可为JSON添加缩进以便阅读，也可压缩成紧凑的单行文本。",steps:["输入JSON文本。","选择美化或压缩。","如有语法错误，先修正再复制结果。"],example:"整理API响应中的嵌套对象和数组，快速查看数据结构。",options:"美化模式提升可读性，压缩模式移除多余空白。",caution:"工具只格式化数据，不会执行或发送JSON。共享屏幕前请隐藏敏感值。"},
  },
  "jpg-to-png": {
    ko:{overview:"JPG 이미지를 투명 배경을 지원하는 PNG 형식으로 변환합니다. JPG 자체의 투명 정보가 복원되는 것은 아닙니다.",steps:["JPG 파일을 선택합니다.","브라우저에서 변환이 끝날 때까지 기다립니다.","미리 보기와 새 PNG 파일을 확인합니다."],example:"문서 편집 도구에서 PNG 형식만 허용하거나 무손실 형식이 필요한 이미지에 사용할 수 있습니다.",options:"변환된 PNG는 픽셀 크기를 유지하며 별도 파일로 다운로드됩니다.",caution:"JPG의 손실 압축 특성은 변환 후에도 되돌아오지 않으며, 파일 용량이 커질 수 있습니다."},
    en:{overview:"Convert a JPG image to PNG. The conversion does not recreate transparency that was not present in the JPG.",steps:["Choose a JPG file.","Wait for the browser to finish converting it.","Preview and download the new PNG."],example:"Use PNG when a document editor requires that format or when you need a lossless output container.",options:"The converted PNG keeps the image dimensions and downloads as a separate file.",caution:"JPG compression cannot be reversed, and the PNG file may be larger."},
    ja:{overview:"JPG画像をPNG形式に変換します。JPGに含まれていない透明情報を復元する機能ではありません。",steps:["JPGファイルを選択します。","ブラウザーでの変換を待ちます。","プレビューを確認して新しいPNGを保存します。"],example:"編集ソフトでPNGが必要な場合や、可逆形式のコンテナが必要な場合に使えます。",options:"画像寸法を保ったPNGを別ファイルとしてダウンロードします。",caution:"JPGの非可逆圧縮は元に戻せず、PNGの容量が大きくなる場合があります。"},
    zh:{overview:"将JPG图像转换为PNG格式。转换无法恢复JPG原本不存在的透明信息。",steps:["选择JPG文件。","等待浏览器完成转换。","预览并下载新的PNG文件。"],example:"当编辑软件要求PNG格式，或需要无损格式容器时可以使用。",options:"转换后的PNG保留图像尺寸，并作为单独文件下载。",caution:"JPG的有损压缩无法恢复，PNG文件体积可能更大。"},
  },
  "png-to-jpg": {
    ko:{overview:"PNG 이미지를 널리 호환되는 JPG 사진 형식으로 변환합니다. 투명 영역은 선택한 배경색으로 채워집니다.",steps:["PNG 파일을 선택합니다.","필요하면 품질 옵션을 조정합니다.","변환된 JPG를 미리 보고 다운로드합니다."],example:"사진 업로드 사이트에서 JPG만 허용하거나 전송 용량을 줄이고 싶을 때 사용할 수 있습니다.",options:"JPG 품질을 조정할 수 있으며 투명 배경은 흰색으로 합성됩니다.",caution:"JPG는 손실 압축 형식이므로 반복 저장하면 화질이 달라질 수 있습니다. 원본 PNG는 변경되지 않습니다."},
    en:{overview:"Convert a PNG image to the widely supported JPG photo format. Transparent areas are filled with a background color.",steps:["Choose a PNG file.","Adjust output quality if needed.","Preview and download the JPG."],example:"Prepare an image for a service that only accepts JPG or reduce its transfer size.",options:"Adjust JPG quality; transparent pixels are composited onto a white background.",caution:"JPG uses lossy compression, so repeated saves can affect detail. Your original PNG remains unchanged."},
    ja:{overview:"PNG画像を幅広く使われるJPG形式に変換します。透明部分は背景色で塗りつぶされます。",steps:["PNGファイルを選択します。","必要に応じて品質を調整します。","変換結果を確認してJPGを保存します。"],example:"JPGのみ対応するサービスへの投稿や、転送容量の調整に使えます。",options:"JPG品質を調整できます。透明部分は白い背景に合成されます。",caution:"JPGは非可逆圧縮形式のため、保存を繰り返すと画質に影響します。元のPNGは変更されません。"},
    zh:{overview:"将PNG图像转换为兼容性广泛的JPG照片格式，透明区域会填充背景色。",steps:["选择PNG文件。","如有需要，调整输出质量。","预览并下载JPG。"],example:"可用于仅接受JPG格式的网站，或调整图片传输体积。",options:"可调整JPG质量，透明像素会合成为白色背景。",caution:"JPG采用有损压缩，重复保存可能影响细节。原始PNG不会修改。"},
  },
  "heic-to-jpg": {
    ko:{overview:"iPhone 등에서 만든 HEIC 사진을 다양한 기기와 웹사이트에서 열기 쉬운 JPG로 변환합니다.",steps:["HEIC 또는 HEIF 사진을 선택합니다.","브라우저에서 변환을 진행합니다.","결과 JPG를 확인하고 저장합니다."],example:"HEIC를 지원하지 않는 Windows 앱이나 웹 업로드 양식에 사진을 제출할 때 유용합니다.",options:"JPG 품질을 조정해 호환성과 용량의 균형을 맞춥니다.",caution:"변환 시 일부 사진 메타데이터가 유지되지 않을 수 있으며 JPG는 손실 압축을 사용합니다. 변환 결과를 확인하세요."},
    en:{overview:"Convert HEIC photos, often created on iPhone, into JPG images that are easier to open across devices and websites.",steps:["Select a HEIC or HEIF photo.","Let the browser convert the image.","Review and save the JPG result."],example:"Prepare a photo for a Windows app or web form that does not accept HEIC.",options:"Adjust JPG quality to balance compatibility and output size.",caution:"Some photo metadata may not be preserved, and JPG uses lossy compression. Review the converted image."},
    ja:{overview:"iPhoneなどで撮影したHEIC写真を、さまざまな端末やWebサイトで開きやすいJPGに変換します。",steps:["HEICまたはHEIF写真を選択します。","ブラウザーで変換します。","結果を確認してJPGを保存します。"],example:"HEIC非対応のWindowsアプリやWebフォームに写真を提出する際に便利です。",options:"JPG品質を調整し、互換性と容量のバランスを取れます。",caution:"一部の写真メタデータが引き継がれない場合があり、JPGは非可逆圧縮です。変換結果をご確認ください。"},
    zh:{overview:"将iPhone等设备生成的HEIC照片转换为更容易在各类设备与网站打开的JPG图像。",steps:["选择HEIC或HEIF照片。","等待浏览器转换图像。","检查并保存JPG结果。"],example:"可为不支持HEIC的Windows应用或网页表单准备照片。",options:"调整JPG质量，在兼容性与文件大小之间取得平衡。",caution:"部分照片元数据可能不会保留，且JPG使用有损压缩。请检查转换结果。"},
  },
  "json-validator": {
    ko:{overview:"JSON 문법이 유효한지 검사하고 파싱 오류가 있으면 확인할 위치를 안내합니다. 데이터를 실행하지 않습니다.",steps:["검사할 JSON을 입력하거나 붙여 넣습니다.","검사 버튼을 눌러 문법을 확인합니다.","오류 위치를 수정하고 다시 검사합니다."],example:"API 설정이나 구성 파일을 저장하기 전에 괄호, 쉼표, 따옴표 오류를 확인할 수 있습니다.",options:"JSON Formatter와 달리 유효성 검사 결과와 오류 확인에 초점을 둡니다.",caution:"문법 검사는 데이터의 의미나 API 호환성까지 보장하지 않습니다. 중요한 구성은 실제 사용 전에 별도 검토하세요."},
    en:{overview:"Check whether JSON syntax is valid and locate parsing errors. The data is not executed.",steps:["Enter or paste JSON to inspect.","Run the syntax check.","Fix the reported issue and check again."],example:"Catch a missing quote, comma, or bracket before saving an API configuration file.",options:"Unlike a formatter, this tool focuses on syntax validity and error feedback.",caution:"Valid syntax does not guarantee the data is semantically correct or accepted by an API. Review important configurations separately."},
    ja:{overview:"JSONの構文が正しいか検証し、解析エラーの位置を確認できます。データを実行することはありません。",steps:["確認するJSONを入力または貼り付けます。","検証を実行します。","表示された箇所を修正して再確認します。"],example:"API設定や構成ファイルを保存する前に、括弧・カンマ・引用符のミスを確認できます。",options:"JSON Formatterとは異なり、構文の有効性とエラー確認に重点を置いています。",caution:"構文が有効でもデータの意味やAPI互換性は保証されません。重要な設定は別途確認してください。"},
    zh:{overview:"检查JSON语法是否有效，并提示解析错误位置。工具不会执行数据。",steps:["输入或粘贴要检查的JSON。","运行语法检查。","修正提示的问题后再次检查。"],example:"保存API配置前检查括号、逗号或引号是否遗漏。",options:"与JSON格式化工具不同，本工具侧重语法有效性和错误提示。",caution:"语法有效不代表数据含义正确或API一定接受。重要配置仍需单独核对。"},
  },
  base64: {
    ko:{overview:"UTF-8 텍스트를 Base64로 인코딩하거나 Base64 문자열을 텍스트로 디코딩합니다.",steps:["인코딩 또는 디코딩 모드를 선택합니다.","텍스트를 입력합니다.","변환 결과를 복사합니다."],example:"테스트 데이터나 간단한 텍스트 값을 Base64 형식으로 확인할 수 있습니다.",options:"UTF-8 텍스트 기준으로 변환하며 인코딩과 디코딩을 전환할 수 있습니다.",caution:"Base64는 암호화가 아니므로 비밀번호나 비밀키를 보호하는 수단으로 사용하지 마세요."},
    en:{overview:"Encode UTF-8 text to Base64 or decode a Base64 string back into text.",steps:["Choose encode or decode mode.","Enter the text.","Copy the converted result."],example:"Inspect a small text value or test payload represented in Base64.",options:"Switch between encoding and decoding; text is interpreted as UTF-8.",caution:"Base64 is not encryption and must not be used to protect passwords or secret keys."},
    ja:{overview:"UTF-8テキストをBase64にエンコード、またはBase64文字列をテキストにデコードします。",steps:["エンコードまたはデコードを選びます。","テキストを入力します。","変換結果をコピーします。"],example:"テストデータや短いテキスト値をBase64形式で確認できます。",options:"UTF-8テキストを基準に、エンコードとデコードを切り替えられます。",caution:"Base64は暗号化ではありません。パスワードや秘密鍵の保護には使わないでください。"},
    zh:{overview:"将UTF-8文本编码为Base64，或将Base64字符串解码回文本。",steps:["选择编码或解码模式。","输入文本。","复制转换结果。"],example:"可检查以Base64表示的测试数据或简短文本。",options:"按UTF-8文本处理，可在编码与解码间切换。",caution:"Base64不是加密方式，不要用它保护密码或密钥。"},
  },
  "uuid-generator": {
    ko:{overview:"Web Crypto 기반으로 충돌 가능성이 매우 낮은 UUID v4 식별자를 생성합니다.",steps:["생성할 UUID 개수를 선택합니다.","생성 버튼을 눌러 식별자를 만듭니다.","필요한 값을 복사해 개발 환경에 사용합니다."],example:"테스트 레코드나 임시 클라이언트 측 식별자가 필요할 때 사용할 수 있습니다.",options:"UUID를 여러 개 한 번에 생성할 수 있습니다.",caution:"UUID는 비밀번호나 인증 토큰이 아닙니다. 보안 비밀값 대신 사용하지 마세요."},
    en:{overview:"Generate UUID v4 identifiers with Web Crypto randomness and an extremely low chance of collision.",steps:["Choose how many UUIDs to create.","Generate the identifiers.","Copy the values into your development workflow."],example:"Create identifiers for test records or temporary client-side objects.",options:"Generate multiple UUIDs in one batch.",caution:"A UUID is not a password or authentication token. Do not use it as a security secret."},
    ja:{overview:"Web Cryptoの乱数を使い、衝突確率が非常に低いUUID v4識別子を生成します。",steps:["生成するUUIDの数を選びます。","生成ボタンで識別子を作成します。","必要な値をコピーして開発に利用します。"],example:"テストデータや一時的なクライアント側オブジェクトの識別子に使えます。",options:"複数のUUIDをまとめて生成できます。",caution:"UUIDはパスワードや認証トークンではありません。秘密情報の代わりに使わないでください。"},
    zh:{overview:"使用Web Crypto随机数生成UUID v4标识符，碰撞概率极低。",steps:["选择要生成的UUID数量。","点击生成标识符。","复制所需值并用于开发流程。"],example:"可为测试记录或临时客户端对象生成标识符。",options:"支持一次生成多个UUID。",caution:"UUID不是密码或身份验证令牌，不要将其用作安全密钥。"},
  },
  "tarot-card": {
    ko:{overview:"타로카드 22장 메이저 아르카나에서 한 장 또는 과거·현재·미래 3장을 뽑아 질문을 돌아보는 시간을 가져 보세요.",steps:["선택적으로 질문과 관심 주제를 입력합니다.","오늘의 카드 한 장 또는 3장 배열을 선택합니다.","카드의 정·역방향 설명과 키워드를 참고합니다."],example:"연애, 금전, 직장·학업에 대한 고민을 확정적인 예언이 아닌 생각 정리의 계기로 살펴볼 수 있습니다.",options:"한 번의 뽑기에서는 카드가 중복되지 않으며 정방향과 역방향이 무작위로 정해집니다.",caution:"질문과 카드는 저장되지 않으며 입력은 이 브라우저에서만 처리됩니다. 타로는 오락과 자기성찰을 위한 참고용입니다."},
    en:{overview:"Draw one card or a three-card past, present, and future spread from the 22 Major Arcana as a prompt for reflection.",steps:["Optionally enter a question and choose a focus.","Select a single daily card or a three-card spread.","Read the upright or reversed interpretation and keywords."],example:"Use a love, money, or work-and-study question as a prompt to organize your thoughts, not as a prediction.",options:"Cards do not repeat within one draw. Upright or reversed orientation is randomized.",caution:"Questions and cards are not saved; input stays in this browser. Tarot is for entertainment and reflection."},
    ja:{overview:"大アルカナ22枚から1枚、または過去・現在・未来の3枚を引き、問いを振り返るきっかけにできます。",steps:["任意で質問とテーマを入力します。","今日の1枚または3枚引きを選びます。","正位置・逆位置の解釈とキーワードを読みます。"],example:"恋愛、金銭、仕事・学業について、予言ではなく考えを整理するヒントとして利用できます。",options:"1回の占いでカードは重複せず、正逆位置はランダムに決まります。",caution:"質問や結果は保存されず、このブラウザー内で処理されます。娯楽と自己理解の参考としてお楽しみください。"},
    zh:{overview:"从22张大阿尔卡那中抽取一张，或使用过去、现在、未来三张牌阵，作为自我反思的提示。",steps:["可选填写问题并选择关注主题。","选择今日单张牌或三张牌阵。","阅读正位或逆位解读及关键词。"],example:"可围绕感情、金钱或工作学习整理想法，但不应将其视为确定预测。",options:"一次抽牌中不会出现重复卡牌，正位或逆位随机决定。",caution:"问题与结果不会保存，输入仅在此浏览器处理。塔罗仅供娱乐和自我反思。"},
  },
  "daily-fortune": {
    ko:{overview:"생년월일과 오늘 날짜를 조합해 종합운, 금전운, 연애운, 직장·학업운과 컨디션을 확인합니다.",steps:["생년월일을 선택합니다.","오늘의 운세 보기를 눌러 결과를 확인합니다.","날짜가 바뀌면 해당 날짜 기준으로 다시 확인할 수 있습니다."],example:"같은 생년월일로 같은 날짜에 다시 조회하면 동일한 문장과 행운 정보를 확인할 수 있습니다.",options:"오늘 날짜 기준으로 결과가 결정되며 행운의 숫자·색과 짧은 메시지도 함께 표시됩니다.",caution:"생년월일은 브라우저에서만 처리하고 저장하지 않습니다. 운세는 오락과 자기성찰을 위한 참고입니다."},
    en:{overview:"Use your birth date and today's date to view an overall reading, money, relationships, work or study, and well-being prompts.",steps:["Choose your date of birth.","Select today's reading to see the result.","Check again on another day for that date's reading."],example:"The same birth date produces the same messages and lucky details when viewed again on the same day.",options:"Today's date determines the result, which also includes a lucky number, color, and short note.",caution:"Your birth date is processed in this browser and is not stored. This reading is for entertainment and reflection."},
    ja:{overview:"生年月日と今日の日付をもとに、総合運、金運、恋愛運、仕事・学業運、コンディションを表示します。",steps:["生年月日を選択します。","今日の運勢を見るボタンを押します。","日付が変わったら、その日の結果を確認できます。"],example:"同じ生年月日で同じ日に再確認すると、同じメッセージとラッキー情報が表示されます。",options:"今日の日付で結果が決まり、ラッキーナンバー・カラーと短いメッセージも表示します。",caution:"生年月日はブラウザー内で処理し、保存しません。娯楽と自己理解の参考としてご利用ください。"},
    zh:{overview:"结合出生日期与当天日期，查看综合、财运、感情、工作学习和状态提示。",steps:["选择出生日期。","点击查看今日运势。","日期变化后，可查看对应日期的新结果。"],example:"相同出生日期在同一天重复查询，会得到相同的文案与幸运信息。",options:"结果根据当天日期生成，并显示幸运数字、幸运颜色和一句寄语。",caution:"出生日期仅在浏览器中处理，不会保存。本结果仅供娱乐和自我反思。"},
  },
  saju: {
    ko:{overview:"한국천문연구원(KASI) 기준 음력 자료와 절기 시각을 사용해 사주 네 기둥인 년주·월주·일주·시주를 계산하고 오행 분포를 확인합니다.",steps:["양력 또는 음력 생년월일과 출생 시각을 입력합니다.","음력이라면 윤달 여부를 정확히 선택합니다.","계산 결과에서 네 기둥과 오행 분포를 확인합니다."],example:"입춘 전후의 출생 시각은 날짜만으로 연주를 정하지 않고 실제 절입 시각을 기준으로 계산합니다.",options:"한국 표준시 기준으로 계산하며, 자시의 날짜 경계는 자정 기준입니다. 오행은 각 기둥의 천간·지지 8글자를 같은 비중으로 세어 표시합니다.",caution:"사주 해석 관습은 학파마다 다를 수 있습니다. 본 도구는 계산 참고용이며 진태양시 보정은 적용하지 않습니다. 입력은 서버에 전송되지 않습니다."},
    en:{overview:"Calculate the year, month, day, and hour pillars using Korean lunar-calendar data based on KASI and solar-term instants, then review the five-element counts.",steps:["Enter a solar or lunar birth date and birth time.","If using the lunar calendar, select whether the month is a leap month.","Review the four pillars and element distribution."],example:"For a birth near Ipchun, the year pillar follows the actual solar-term instant rather than changing solely at midnight on a date.",options:"The chart uses Korea Standard Time and a midnight day-boundary convention. Each of the eight stem and branch characters contributes one count to the element summary.",caution:"Interpretive conventions can differ between schools. This is a calculation reference, does not apply true-solar-time correction, and keeps input in your browser."},
    ja:{overview:"KASI基準の韓国暦データと節入り時刻を使って、年柱・月柱・日柱・時柱を計算し、五行の数を確認できます。",steps:["太陽暦または太陰暦の生年月日と出生時刻を入力します。","太陰暦の場合は閏月かどうかを正しく選びます。","四柱と五行の分布を確認します。"],example:"立春の前後に生まれた場合、日付だけで年柱を切り替えず、実際の節入り時刻を基準に計算します。",options:"韓国標準時と午前0時の日界を使用します。五行は四柱の天干・地支、計8字を同じ重みで数えます。",caution:"解釈の慣例は流派によって異なります。計算参考用であり、真太陽時補正は適用しません。入力はサーバーへ送信されません。"},
    zh:{overview:"使用基于KASI资料的韩国阴历数据与节气交接时刻，计算年柱、月柱、日柱、时柱并查看五行计数。",steps:["输入公历或农历出生日期与时间。","若选择农历，请准确选择是否为闰月。","查看四柱与五行分布。"],example:"出生时间接近立春时，年柱依据实际节气交接时刻计算，而不是简单按日期午夜切换。",options:"采用韩国标准时间与午夜换日规则。五行统计将四柱的天干地支共八字等权计数。",caution:"不同流派的解释惯例可能不同。本工具用于计算参考，不进行真太阳时校正，输入不会发送到服务器。"},
  },
};

const headings: Record<Locale, {overview:string;how:string;example:string;options:string;privacy:string;warning:string;faq:string;privacyQuestion:string;privacyAnswer:string}> = {
 ko:{overview:"도구 안내",how:"사용 방법",example:"사용 예",options:"주요 옵션",privacy:"개인정보 처리",warning:"참고 사항",faq:"자주 묻는 질문",privacyQuestion:"입력한 정보가 서버로 전송되나요?",privacyAnswer:"아니요. 입력과 처리는 사용 중인 브라우저에서 이루어집니다."},
 en:{overview:"About this tool",how:"How to use",example:"Example",options:"Options",privacy:"Privacy",warning:"Please note",faq:"Frequently asked questions",privacyQuestion:"Is my input sent to a server?",privacyAnswer:"No. Your input is handled in the browser you are using."},
 ja:{overview:"ツールについて",how:"使い方",example:"使用例",options:"主な設定",privacy:"プライバシー",warning:"ご利用時の注意",faq:"よくある質問",privacyQuestion:"入力内容はサーバーに送信されますか？",privacyAnswer:"いいえ。入力と処理は利用中のブラウザー内で行われます。"},
 zh:{overview:"工具说明",how:"使用方法",example:"使用示例",options:"主要选项",privacy:"隐私处理",warning:"注意事项",faq:"常见问题",privacyQuestion:"输入内容会发送到服务器吗？",privacyAnswer:"不会。输入与处理均在当前浏览器中完成。"},
};

export function getToolContent(slug:string,locale:Locale) { const copy=content[slug]?.[locale]; return copy ? { ...copy, headings:headings[locale] } : undefined; }
