import type { ToolCategory } from "./categories";

export type ToolDefinition = {
  id: string; slug: string; category: ToolCategory; title: string; shortTitle: string;
  description: string; keywords: string[]; clientOnly: true; isPublic: boolean; acceptedTypes?: string[]; relatedTools?: string[];
};

const entries: Array<[string, ToolCategory, string, string, string[], boolean]> = [
  ["lotto-number-generator","random","로또 번호 생성기","중복 없이 무작위 로또 번호를 만듭니다.",["로또","번호 생성","lotto"],true],
  ["random-number","random","랜덤 숫자 뽑기","범위와 개수를 정해 중복 여부를 선택하며 숫자를 추첨합니다.",["랜덤","숫자","추첨","random number"],true],
  ["random-name-picker","random","랜덤 이름 뽑기","이름 목록에서 원하는 인원을 무작위로 뽑습니다.",["랜덤 이름","이름 추첨","random name"],true],
  ["random-wheel","random","룰렛 돌리기","항목을 입력하고 온라인 룰렛으로 하나를 선택합니다.",["룰렛","랜덤 룰렛","온라인 룰렛","random wheel"],true],
  ["draw-lots","random","제비뽑기","참가자 목록에서 당첨자를 무작위로 선정합니다.",["제비뽑기","당첨자","추첨"],true],
  ["random-team-maker","random","랜덤 팀 나누기","참가자를 균등하게 섞어 팀을 편성합니다.",["팀 나누기","조 편성","랜덤 조 편성"],true],
  ["random-order","random","랜덤 순서 정하기","발표나 진행 순서를 무작위로 정합니다.",["순서 정하기","발표 순서","셔플"],true],
  ["random-seat","random","랜덤 자리 배치","참가자 이름을 섞어 무작위 자리 순서를 배정합니다.",["랜덤 자리 배치","자리 추첨","좌석 배정"],true],
  ["duty-picker","random","당번 정하기","참가자와 할 일을 입력해 공정하게 당번을 배정합니다.",["당번 정하기","청소 당번","역할 배정"],true],
  ["dice-roller","random","주사위 굴리기","D4부터 D20까지 주사위를 굴리고 합계를 확인합니다.",["주사위","dice","랜덤"],true],
  ["coin-flip","random","동전 던지기","동전을 여러 번 던지고 앞면과 뒷면 횟수를 확인합니다.",["동전 던지기","앞면","뒷면"],true],
  ["stopwatch","date-time","스톱워치","밀리초 단위로 시간을 재고 랩 기록을 남깁니다.",["스톱워치","초시계","stopwatch"],true],
  ["timer","date-time","온라인 타이머","시·분·초를 설정해 브라우저에서 타이머를 실행합니다.",["타이머","온라인 타이머","무료 타이머"],true],
  ["pomodoro-timer","date-time","뽀모도로 타이머","집중과 휴식 시간을 번갈아 관리합니다.",["뽀모도로","집중 타이머","pomodoro"],true],
  ["world-clock","date-time","세계 시간","주요 도시의 현재 시간을 브라우저 시간대로 확인합니다.",["세계 시간","도시 시간","timezone"],true],
  ["password-generator","utility","비밀번호 생성기","Web Crypto 기반으로 안전한 무작위 비밀번호를 만듭니다.",["비밀번호","암호 생성","password"],true],
  ["random-string-generator","utility","랜덤 문자열 생성기","문자 종류와 길이를 선택해 무작위 문자열을 생성합니다.",["랜덤 문자열","문자열 생성"],true],
  ["wifi-qr","utility","Wi-Fi QR 코드 생성기","네트워크 정보를 QR 코드로 만들어 빠르게 Wi-Fi에 연결합니다.",["Wi-Fi QR","와이파이 QR","무선 인터넷"],true],
  ["contact-qr","utility","연락처 QR 코드 생성기","이름과 연락처를 vCard QR 코드로 만듭니다.",["연락처 QR","명함 QR","vCard"],true],
  ["phone-qr","utility","전화번호 QR 코드 생성기","스캔하면 전화 앱을 여는 전화번호 QR 코드를 만듭니다.",["전화 QR","전화번호 QR","tel QR"],true],
  ["email-qr","utility","이메일 QR 코드 생성기","받는 사람과 제목을 포함한 이메일 작성 QR 코드를 만듭니다.",["이메일 QR","메일 QR","mailto"],true],
  ["barcode-checker","utility","바코드 번호 검사","EAN-13과 UPC-A 체크섬이 올바른지 확인합니다.",["barcode","EAN-13","UPC-A"],true],
  ["barcode-generator","utility","바코드 생성기","텍스트나 상품 번호로 CODE128 또는 EAN-13 바코드를 만듭니다.",["바코드 생성","CODE128","EAN-13"],true],
  ["social-image-resize","image","SNS 이미지 크기 변경","SNS 게시물과 스토리에 맞는 이미지 크기로 조정합니다.",["인스타그램 크기","유튜브 썸네일","SNS 이미지"],true],
  ["add-text-to-image","image","이미지에 텍스트 추가","브라우저 캔버스에서 이미지에 문구를 넣어 저장합니다.",["이미지 글자","사진 문구"],true],
  ["file-hash","utility","파일 해시 계산","파일을 업로드하지 않고 브라우저에서 SHA 해시를 계산합니다.",["SHA-256","파일 해시","checksum"],true],
  ["mime-type-checker","utility","MIME 타입 확인","브라우저가 감지한 MIME 타입과 파일 시그니처를 확인합니다.",["MIME","파일 형식","file type"],true],
  ["file-extension-checker","utility","파일 확장자 확인","선택한 파일의 확장자와 브라우저 MIME 타입을 확인합니다.",["확장자","파일 형식"],true],
  ["file-size-checker","utility","파일 크기 확인","여러 파일의 이름과 크기를 브라우저에서 확인합니다.",["파일 크기","용량"],true],
  ["duplicate-file-checker","utility","중복 파일 찾기","SHA-256 내용 해시를 비교해 내용이 같은 파일을 찾습니다.",["중복 파일","파일 중복 검사","duplicate files"],true],
  ["zip-files","utility","ZIP 파일 만들기","선택한 파일을 브라우저에서 하나의 ZIP 파일로 묶습니다.",["ZIP 만들기","파일 압축","zip files"],true],
  ["bulk-file-renamer","utility","파일명 일괄 변경","파일 이름 규칙을 적용한 복사본을 ZIP으로 다운로드합니다.",["파일명 일괄 변경","파일 이름 바꾸기"],true],
  ["filename-cleaner","utility","파일명 정리","파일 이름의 공백과 특수문자를 정리한 ZIP을 만듭니다.",["파일명 정리","파일 이름 정리"],true],
  ["name-sorter","text","이름 정렬","이름 목록을 언어에 맞는 가나다·알파벳 순으로 정렬합니다.",["이름 정렬","가나다 정렬","이름 가나다순"],true],
  ["shuffle-lines","text","텍스트 줄 섞기","입력한 줄을 무작위 순서로 섞습니다.",["줄 섞기","텍스트 셔플"],true],
  ["add-line-numbers","text","줄 번호 붙이기","각 줄 앞에 시작 번호와 구분자를 추가합니다.",["줄 번호","라인 넘버"],true],
  ["remove-line-numbers","text","줄 번호 제거","일반적인 형식의 줄 번호를 텍스트에서 제거합니다.",["줄 번호 제거"],true],
  ["remove-empty-lines","text","빈 줄 제거","내용이 없는 줄만 제거하고 나머지 줄바꿈은 유지합니다.",["빈 줄 제거","공백 줄"],true],
  ["remove-characters","text","특정 문자 제거","숫자, 영문, 한글, 특수문자 또는 지정 문자를 제거합니다.",["문자 제거","특수문자 제거"],true],
  ["text-repeater","text","텍스트 반복","텍스트를 원하는 횟수만큼 반복하고 구분자를 추가합니다.",["텍스트 반복","문장 반복"],true],
  ["text-to-file","text","텍스트 파일 만들기","입력한 내용을 TXT 또는 CSV 파일로 저장합니다.",["텍스트 파일","TXT 저장","CSV 만들기"],true],
  ["lorem-ipsum","developer","Lorem Ipsum 생성기","레이아웃 시안에 사용할 더미 텍스트를 생성합니다.",["lorem ipsum","더미 텍스트"],true],
  ["regex-tester","developer","정규식 테스트","샘플 텍스트에서 정규식 일치 결과를 확인합니다.",["regex","정규식 검사"],true],
  ["color-converter","developer","HEX RGB 색상 변환","HEX, RGB, HSL 색상 값을 서로 변환합니다.",["HEX RGB 변환","색상 코드","HSL"],true],
  ["cron-parser","developer","Cron 표현식 해석기","5필드 또는 6필드 Cron 표현식을 검사하고 다음 실행 시간을 확인합니다.",["cron","crontab","작업 스케줄"],true],
  ["sql-formatter","developer","SQL 포맷터","SQL 쿼리를 읽기 좋게 정리합니다. 쿼리를 실행하지 않습니다.",["SQL 정렬","SQL formatter"],true],
  ["html-formatter","developer","HTML 포맷터","HTML 코드를 브라우저에서 들여쓰기 정리합니다. 코드를 실행하지 않습니다.",["HTML 정렬","HTML formatter"],true],
  ["css-formatter","developer","CSS 포맷터","CSS 코드를 보기 좋게 정리합니다.",["CSS 정렬","CSS formatter"],true],
  ["javascript-formatter","developer","JavaScript 포맷터","JavaScript 코드를 실행하지 않고 포맷팅합니다.",["JS 정렬","JavaScript formatter"],true],
  ["markdown-preview","developer","Markdown 미리보기","Markdown을 안전하게 미리 보고 원본 HTML은 실행하지 않습니다.",["Markdown 미리보기","마크다운 뷰어"],true],
  ["jpg-to-png","image","JPG → PNG 변환","JPG 이미지를 PNG 형식으로 변환합니다.",["jpg","jpeg","png","convert"], true],
  ["png-to-jpg","image","PNG → JPG 변환","PNG 이미지를 JPG로 변환합니다. 투명한 부분은 흰색으로 채웁니다.",["png","jpg","jpeg","convert"], true],
  ["webp-to-jpg","image","WEBP → JPG 변환","WEBP 이미지를 JPG 파일로 변환합니다.",["webp","jpg","convert"], true],
  ["webp-to-png","image","WEBP → PNG 변환","WEBP 이미지를 PNG 파일로 변환합니다.",["webp","png","convert"], true],
  ["jpg-to-webp","image","JPG → WEBP 변환","JPG 이미지를 WEBP 형식으로 변환합니다.",["jpg","jpeg","webp","convert"], true],
  ["png-to-webp","image","PNG → WEBP 변환","PNG 이미지를 WEBP 형식으로 변환합니다.",["png","webp","convert"], true],
  ["heic-to-jpg","image","HEIC → JPG 변환","HEIC 사진을 JPG 이미지로 변환합니다.",["heic","heif","jpg","iphone"], true],
  ["image-compress","image","이미지 압축","품질을 조절해 이미지 파일 크기를 줄입니다.",["compress","quality","용량"], true],
  ["image-resize","image","이미지 크기 조절","가로·세로 크기와 비율을 설정해 이미지를 조절합니다.",["resize","width","height"], true],
  ["image-crop","image","이미지 자르기","가로세로 비율과 위치를 정해 이미지 중앙을 자릅니다.",["crop","자르기"], true],
  ["image-rotate","image","이미지 회전","이미지를 90도, 180도 또는 270도 회전합니다.",["rotate","회전"], true],
  ["image-flip","image","이미지 뒤집기","이미지를 가로 또는 세로 방향으로 뒤집습니다.",["flip","mirror"], true],
  ["image-grayscale","image","이미지 흑백 변환","컬러 이미지를 흑백으로 변환합니다.",["grayscale","흑백"], true],
  ["image-brightness","image","이미지 밝기 조절","이미지 밝기를 조절합니다.",["brightness","밝기"], true],
  ["image-contrast","image","이미지 대비 조절","이미지의 명암 대비를 조절합니다.",["contrast","대비"], true],
  ["image-blur","image","이미지 흐리게","이미지에 부드러운 흐림 효과를 적용합니다.",["blur","흐림"], true],
  ["image-pixelate","image","이미지 모자이크","이미지에 모자이크 효과를 적용합니다.",["pixelate","mosaic","모자이크"], true],
  ["remove-image-metadata","image","이미지 메타데이터 제거","이미지를 다시 인코딩해 EXIF 및 GPS 메타데이터를 제거합니다.",["metadata","exif","gps"], true],
  ["image-info","image","이미지 정보 확인","이미지 크기와 형식, 비율, 파일 용량을 확인합니다.",["image","info","size"], true],
  ["favicon-generator","image","Favicon 생성기","이미지로 브라우저용 favicon PNG를 만듭니다.",["favicon","icon"], true],
  ["image-color-picker","image","이미지 색상 추출","이미지를 눌러 색상의 HEX와 RGB 값을 확인합니다.",["color picker","hex","rgb"], true],
  ["images-to-pdf","image","이미지 PDF 변환","여러 이미지를 하나의 PDF 문서로 만듭니다.",["images","pdf","merge"], true],
  ["pdf-merge","pdf","PDF 합치기","여러 PDF 파일을 선택한 순서대로 합칩니다.",["pdf","merge","병합"], true],
  ["pdf-split","pdf","PDF 페이지 추출","페이지 범위를 입력해 새 PDF로 저장합니다.",["pdf","split","extract"], true],
  ["pdf-delete-pages","pdf","PDF 페이지 삭제","지정한 페이지를 제외한 PDF를 만듭니다.",["pdf","delete","pages"], true],
  ["pdf-reorder-pages","pdf","PDF 페이지 순서 변경","페이지 번호 순서를 입력해 PDF 페이지를 재배치합니다.",["pdf","reorder","pages"], true],
  ["pdf-rotate-pages","pdf","PDF 페이지 회전","모든 PDF 페이지를 90도 단위로 회전합니다.",["pdf","rotate"], true],
  ["pdf-add-page-numbers","pdf","PDF 페이지 번호 추가","PDF 각 페이지 아래쪽에 페이지 번호를 추가합니다.",["pdf","page numbers"], true],
  ["pdf-watermark","pdf","PDF 워터마크","텍스트 워터마크를 PDF 모든 페이지에 추가합니다.",["pdf","watermark"], true],
  ["pdf-metadata-viewer","pdf","PDF 메타데이터 확인","PDF 문서의 제목, 작성자 등 메타데이터를 확인합니다.",["pdf","metadata"], true],
  ["pdf-remove-metadata","pdf","PDF 메타데이터 제거","PDF의 문서 메타데이터를 제거한 사본을 만듭니다.",["pdf","metadata","privacy"], true],
  ["character-count","text","글자 수 세기","글자 수와 줄 수, 단어 수를 계산합니다.",["character","count","글자수"], true],
  ["remove-spaces","text","공백 제거","텍스트의 공백을 모두 제거하거나 연속 공백을 정리합니다.",["spaces","공백"], true],
  ["remove-line-breaks","text","줄바꿈 제거","텍스트의 줄바꿈을 공백으로 바꿉니다.",["line break","줄바꿈"], true],
  ["remove-duplicate-lines","text","중복 줄 제거","반복되는 줄을 하나만 남깁니다.",["duplicate","lines"], true],
  ["sort-lines","text","줄 정렬","텍스트 줄을 오름차순 또는 내림차순으로 정렬합니다.",["sort","lines"], true],
  ["text-case-converter","text","대소문자 변환","영문 텍스트를 소문자, 대문자, 제목 형식으로 바꿉니다.",["case","uppercase","lowercase"], true],
  ["text-compare","text","텍스트 비교","두 텍스트를 비교하고 달라진 줄을 표시합니다.",["diff","compare"], true],
  ["reverse-text","text","텍스트 뒤집기","문자 순서를 반대로 바꿉니다.",["reverse","text"], true],
  ["remove-duplicate-words","text","중복 단어 제거","문장 안에서 반복되는 단어를 제거합니다.",["duplicate","words"], true],
  ["json-formatter","developer","JSON Formatter","JSON을 보기 좋게 정렬하거나 압축하고 복사합니다.",["json","format","minify"], true],
  ["json-validator","developer","JSON Validator","JSON 문법을 검사하고 오류 위치를 안내합니다.",["json","validate"], true],
  ["json-to-yaml","developer","JSON → YAML","JSON 데이터를 YAML 형식으로 변환합니다.",["json","yaml","convert"], true],
  ["yaml-to-json","developer","YAML → JSON","YAML 데이터를 JSON 형식으로 변환합니다.",["yaml","json","convert"], true],
  ["csv-to-json","developer","CSV → JSON","CSV 표 데이터를 JSON 배열로 변환합니다.",["csv","json","convert"], true],
  ["json-to-csv","developer","JSON → CSV","객체 배열 JSON을 CSV 표로 변환합니다.",["json","csv","convert"], true],
  ["base64","developer","Base64 인코더·디코더","UTF-8 텍스트를 Base64로 인코딩하거나 디코딩합니다.",["base64","encode","decode"], true],
  ["url-encode-decode","developer","URL 인코더·디코더","URL 텍스트를 인코딩하거나 디코딩합니다.",["url","encode","decode"], true],
  ["uuid-generator","developer","UUID 생성기","Web Crypto API로 UUID를 여러 개 생성합니다.",["uuid","guid","random"], true],
  ["timestamp-converter","developer","Timestamp 변환기","Unix 초·밀리초와 날짜, ISO 8601 시간을 변환합니다.",["timestamp","unix","iso 8601"], true],
];

const registeredTools: ToolDefinition[] = entries.map(([slug, category, title, description, keywords, isPublic]) => ({ id: slug, slug, category, title, shortTitle: title, description, keywords, clientOnly: true, isPublic, acceptedTypes: category === "image" ? ["image/*"] : category === "pdf" ? ["application/pdf"] : undefined }));
export const filterPublicTools = (items: ToolDefinition[]) => items.filter((tool) => tool.isPublic);
export const tools = filterPublicTools(registeredTools);
const slugPattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const duplicateSlugs = tools.map((tool) => tool.slug).filter((slug, i, all) => all.indexOf(slug) !== i);
if (duplicateSlugs.length || tools.some((tool) => !slugPattern.test(tool.slug))) throw new Error(`Invalid or duplicate tool slug: ${duplicateSlugs.join(", ")}`);
for (const tool of tools) tool.relatedTools = tools.filter((other) => other.category === tool.category && other.slug !== tool.slug).slice(0, 4).map((other) => other.slug);
export const getTool = (slug: string) => tools.find((tool) => tool.slug === slug);
